import { all, first } from "@/db/lms";
import { LmsShell, Status, activityIcon, formatDate } from "../components";
import { requireRole } from "../auth";
import DashboardInsights from "../DashboardInsights";

type Course={id:string;title:string;subject:string;level:string;accent:string;progress:number;tutor:string};
type ClassItem={id:string;title:string;starts_at:string;duration_minutes:number;meeting_url:string;course:string;tutor:string};
type Task={id:string;title:string;type:string;due_at:string;points:number;course:string;submission_status:string|null};
type Badge={id:string;name:string;description:string;icon:string;xp_required:number;awarded_at:string|null};
type Game={xp:number;level:number;streak_days:number};
type Entitlement={plan_type:string;class_allowance:number;expires_at:string};
export const dynamic="force-dynamic";

export default async function StudentDashboard(){
  const profile=await requireRole("student","/dashboard/student");const studentId=profile.role==='admin'?'usr_demo_student':profile.id;
  const timezone=(await first<{timezone:string}>("SELECT timezone FROM user_profiles WHERE user_id=?",studentId))?.timezone??"Asia/Kolkata";
  const courses=await all<Course>(`SELECT c.id,c.title,c.subject,c.level,c.accent,e.progress,u.name tutor FROM enrollments e JOIN courses c ON c.id=e.course_id LEFT JOIN users u ON u.id=c.tutor_id WHERE e.student_id=? AND c.status='active' ORDER BY e.created_at`,studentId);
  const classes=await all<ClassItem>(`SELECT l.id,l.title,l.starts_at,l.duration_minutes,l.meeting_url,c.title course,u.name tutor FROM live_classes l JOIN courses c ON c.id=l.course_id JOIN users u ON u.id=l.tutor_id WHERE (l.student_id=? OR (l.student_id IS NULL AND l.course_id IN (SELECT course_id FROM enrollments WHERE student_id=?))) AND l.status='scheduled' ORDER BY l.starts_at ASC LIMIT 4`,studentId,studentId);
  const tasks=await all<Task>(`SELECT a.id,a.title,a.type,a.due_at,a.points,c.title course,s.status submission_status FROM activities a JOIN courses c ON c.id=a.course_id JOIN enrollments e ON e.course_id=a.course_id AND e.student_id=? LEFT JOIN chapters ch ON ch.id=a.chapter_id LEFT JOIN submissions s ON s.activity_id=a.id AND s.student_id=? WHERE a.status='published' AND a.is_unlocked=1 AND c.is_unlocked=1 AND (a.chapter_id IS NULL OR ch.is_unlocked=1) ORDER BY CASE WHEN s.id IS NULL THEN 0 ELSE 1 END,a.due_at ASC LIMIT 6`,studentId,studentId);
  const badges=await all<Badge>(`SELECT b.id,b.name,b.description,b.icon,b.xp_required,sb.awarded_at FROM badges b LEFT JOIN student_badges sb ON sb.badge_id=b.id AND sb.student_id=? ORDER BY b.xp_required`,studentId);
  const game=await first<Game>("SELECT xp,level,streak_days FROM student_gamification WHERE student_id=?",studentId)??{xp:0,level:1,streak_days:0};
  const certificates=await first<{total:number}>("SELECT COUNT(*) total FROM certificates WHERE student_id=?",studentId);const entitlement=await first<Entitlement>("SELECT plan_type,class_allowance,expires_at FROM student_subscriptions WHERE student_id=?",studentId);const used=await first<{total:number}>("SELECT COUNT(DISTINCT id) total FROM live_classes WHERE (student_id=? OR (student_id IS NULL AND course_id IN (SELECT course_id FROM enrollments WHERE student_id=?))) AND status='completed'",studentId,studentId);const learning=await first<{quiz_score:number;submitted:number;reviewed:number}>(`SELECT COALESCE(ROUND((SELECT AVG(score*100.0/NULLIF(max_score,0)) FROM quiz_attempts WHERE student_id=?)),0) quiz_score,(SELECT COUNT(*) FROM submissions WHERE student_id=?) submitted,(SELECT COUNT(*) FROM submissions WHERE student_id=? AND status='reviewed') reviewed`,studentId,studentId,studentId);const classesTaken=used?.total??0;const classesRemaining=Math.max(0,(entitlement?.class_allowance??0)-classesTaken);const nextClass=classes[0];const levelXp=game.xp%100;const pending=tasks.filter(task=>!task.submission_status);const avgProgress=courses.length?courses.reduce((sum,item)=>sum+item.progress,0)/courses.length:0;
  return <LmsShell profile={profile} activeRole="student" eyebrow="Your learning adventure" title={`Welcome back, ${profile.name.split(' ')[0]}!`} subtitle="Complete lessons, collect XP, unlock badges and turn every course into an achievement." actions={nextClass?.meeting_url?<a className="primary-action" href={nextClass.meeting_url}>Join next class ↗</a>:undefined}>
    <section className="game-hero"><div className="game-level"><span>LEVEL</span><strong>{game.level}</strong></div><div className="game-copy"><span className="game-chip">🔥 {game.streak_days} day streak</span><h2>{levelXp<75?'Your next level is within reach!':'Almost there — one more push!'}</h2><p>Every completed lesson earns 50 XP. Keep learning to unlock your next badge.</p><div className="xp-track"><i style={{width:`${levelXp}%`}}/></div><small><b>{levelXp} XP</b> / 100 XP to Level {game.level+1}</small></div><div className="game-trophy">🏆<b>{game.xp}</b><span>Total XP</span></div></section>
    <div className="game-stat-grid"><a href="/dashboard/student/curriculum"><span>⚡</span><strong>{courses.length}</strong><small>Active courses</small></a><a href="/dashboard/student/quizzes"><span>🎯</span><strong>{pending.length}</strong><small>Tasks to conquer</small></a><a href="/dashboard/student/classes"><span>✓</span><strong>{classesTaken}</strong><small>Classes taken</small></a><a href="/dashboard/student/classes"><span>⏳</span><strong>{classesRemaining}</strong><small>Classes remaining</small></a><a href="/dashboard/student/certificates"><span>🎓</span><strong>{certificates?.total??0}</strong><small>Certificates earned</small></a><a href="/dashboard/student/classes"><span>📅</span><strong>{classes.length}</strong><small>Upcoming classes</small></a></div>
    <DashboardInsights eyebrow="MY LEARNING MAP" title="See how your skills are growing" subtitle="Your progress web combines lessons, quiz understanding, completed work, attendance and learning consistency." axes={[{label:"Lessons",value:avgProgress},{label:"Understanding",value:learning?.quiz_score??0},{label:"Assignments",value:tasks.length?((tasks.length-pending.length)/tasks.length)*100:(learning?.submitted?80:0)},{label:"Attendance",value:entitlement?.class_allowance?(classesTaken/entitlement.class_allowance)*100:0},{label:"Consistency",value:Math.min(100,game.streak_days*14)}]} donutValue={entitlement?.class_allowance?(classesTaken/entitlement.class_allowance)*100:0} donutLabel="Classes used" donutNote={`${classesTaken} taken · ${classesRemaining} remaining in your current plan.`} trend={courses.length?courses.map(item=>item.progress):[12,24,38,51,63,74]}/>
    <div className="dashboard-grid student-grid"><section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">NEXT QUESTS</span><h2>Keep your momentum</h2></div><Status tone="amber">{pending.length} open</Status></div><div className="quest-list">{tasks.map(task=><a className={task.submission_status?'quest done':'quest'} href="/dashboard/student/work" key={task.id}><span className={`activity-symbol ${task.type}`}>{activityIcon(task.type)}</span><div><small>{task.type} · {task.course}</small><strong>{task.title}</strong><p>Due {formatDate(task.due_at)} · up to {task.points} points</p></div><b>{task.submission_status?'✓ Done':'Start →'}</b></a>)}</div></section>
      <section className="panel"><div className="panel-head"><div><span className="panel-kicker">BADGE CABINET</span><h2>Your achievements</h2></div><a className="subtle-link" href="/dashboard/student/progress">View progress →</a></div><div className="badge-grid">{badges.map(badge=><article className={badge.awarded_at?'badge earned':'badge locked'} key={badge.id}><span>{badge.icon}</span><div><strong>{badge.name}</strong><small>{badge.awarded_at?badge.description:`Unlock at ${badge.xp_required} XP`}</small></div></article>)}</div></section>
      <section className="panel"><div className="panel-head"><div><span className="panel-kicker">MY COURSES</span><h2>Learning worlds</h2></div></div><div className="progress-list">{courses.map(course=><a href="/dashboard/student/curriculum" key={course.id}><div className={`course-mini ${course.accent}`}>{course.subject.slice(0,2).toUpperCase()}</div><div><strong>{course.title}</strong><small>{course.level} · {course.tutor}</small><div className="mini-progress"><i style={{width:`${course.progress}%`}}/></div><span>{course.progress}% complete</span></div></a>)}</div></section>
      <section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">UPCOMING 1:1 CLASSES · {timezone}</span><h2>Your learning calendar</h2></div><a className="subtle-link" href="/dashboard/student/classes">Full calendar →</a></div><div className="game-class-list">{classes.map(item=><article key={item.id}><div><strong>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,day:'numeric'}).format(new Date(item.starts_at))}</strong><span>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,month:'short'}).format(new Date(item.starts_at))}</span></div><p><small>{item.course}</small><b>{item.title}</b><span>{formatDate(item.starts_at,timezone)} · {item.tutor}</span></p>{item.meeting_url?<a href={item.meeting_url}>Join ↗</a>:<Status tone="blue">Scheduled</Status>}</article>)}</div></section>
    </div>
  </LmsShell>;
}
