ALTER TABLE users ADD COLUMN public_id TEXT;
CREATE UNIQUE INDEX IF NOT EXISTS idx_users_public_id ON users(public_id);
UPDATE users SET public_id='SKV-TUT-' || upper(substr(hex(randomblob(4)),1,8)) WHERE role='tutor' AND public_id IS NULL;
UPDATE users SET public_id='SKV-STU-' || upper(substr(hex(randomblob(4)),1,8)) WHERE role='student' AND public_id IS NULL;
UPDATE users SET public_id='SKV-MGR-' || upper(substr(hex(randomblob(4)),1,8)) WHERE role='manager' AND public_id IS NULL;
UPDATE users SET public_id='SKV-ADM-' || upper(substr(hex(randomblob(4)),1,8)) WHERE role='admin' AND public_id IS NULL;
ALTER TABLE user_profiles ADD COLUMN headline TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN qualifications TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN experience_years INTEGER NOT NULL DEFAULT 0;
ALTER TABLE user_profiles ADD COLUMN specialties TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN achievements TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN teaching_philosophy TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN location TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN languages TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN linkedin_url TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN website_url TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN avatar_r2_key TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN avatar_content_type TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN avatar_file_name TEXT NOT NULL DEFAULT '';
ALTER TABLE user_profiles ADD COLUMN is_public INTEGER NOT NULL DEFAULT 1;
CREATE TABLE IF NOT EXISTS ai_provider_credentials (provider TEXT PRIMARY KEY, encrypted_key TEXT NOT NULL, iv TEXT NOT NULL, key_hint TEXT NOT NULL DEFAULT '', updated_by TEXT NOT NULL REFERENCES users(id), updated_at TEXT NOT NULL);
PRAGMA optimize;
