import { first } from "@/db/lms";
import { BadgeCheck, Camera, ExternalLink, IdCard } from "lucide-react";
import { LmsShell, Metric, Notice, Status, initials } from "../components";
import { requireProfile } from "../auth";
import { supportedTimeZones } from "@/db/timezones";

type Details={phone:string;timezone:string;bio:string;preferred_language:string;headline:string;qualifications:string;experience_years:number;specialties:string;achievements:string;teaching_philosophy:string;location:string;languages:string;linkedin_url:string;website_url:string;avatar_r2_key:string;is_public:number;intro_video_url:string;subject_areas:string;grade_levels:string;certifications:string};
export const dynamic="force-dynamic";
export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireProfile("/dashboard/profile");const details=await first<Details>("SELECT * FROM user_profiles WHERE user_id=?",profile.id);const workspace=profile.role==='manager'?'admin':profile.role;let stats:{primary:number;secondary:number;tertiary:number};
  if(profile.role==='student'){const id=profile.id;const row=await first<{courses:number;lessons:number;classes:number}>(`SELECT (SELECT COUNT(*) FROM enrollments WHERE student_id=?) courses,(SELECT COUNT(*) FROM lesson_progress WHERE student_id=?) lessons,(SELECT COUNT(*) FROM live_classes WHERE student_id=? AND status='completed') classes`,id,id,id);stats={primary:row?.courses??0,secondary:row?.lessons??0,tertiary:row?.classes??0};}
  else if(profile.role==='tutor'){const id=profile.id;const row=await first<{courses:number;students:number;classes:number}>(`SELECT (SELECT COUNT(*) FROM courses WHERE tutor_id=? AND status='active') courses,(SELECT COUNT(DISTINCT e.student_id) FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE c.tutor_id=?) students,(SELECT COUNT(*) FROM live_classes WHERE tutor_id=? AND status='completed') classes`,id,id,id);stats={primary:row?.courses??0,secondary:row?.students??0,tertiary:row?.classes??0};}
  else {const row=await first<{users:number;courses:number;classes:number}>(`SELECT (SELECT COUNT(*) FROM users) users,(SELECT COUNT(*) FROM courses WHERE status='active') courses,(SELECT COUNT(*) FROM live_classes) classes`);stats={primary:row?.users??0,secondary:row?.courses??0,tertiary:row?.classes??0};}
  const publicHref=profile.role==='tutor'&&profile.public_id?`/tutors/${profile.public_id}`:undefined;
  return <LmsShell profile={profile} activeRole={workspace} activePath="/dashboard/profile" eyebrow="My identity" title={profile.role==='tutor'?"Profile & public teaching portfolio":"Profile & preferences"} subtitle={profile.role==='tutor'?"Build a trusted digital CV that automatically powers your public Skillvelop tutor page.":"Keep your contact details and learning preferences up to date."} actions={publicHref?<a className="primary-action" href={publicHref} target="_blank" rel="noreferrer">View public profile <ExternalLink size={16}/></a>:undefined}>
    <Notice params={await searchParams}/><section className="profile-hero">{details?.avatar_r2_key&&profile.public_id?<img src={`/api/profile-photo/${profile.public_id}`} alt={`${profile.name} profile`}/>:<span>{initials(profile.name)}</span>}<div><Status>{profile.status}</Status><h2>{profile.name}</h2><p>{details?.headline||profile.email}</p><small><IdCard size={14}/> {profile.public_id??"ID preparing"} · {profile.role} · Member since {new Date(profile.created_at).toLocaleDateString('en-IN',{month:'long',year:'numeric'})}</small></div>{profile.role==='tutor'&&<BadgeCheck className="profile-verified" size={36}/>}</section>
    <div className="metrics-grid profile-metrics"><Metric label={profile.role==='student'?'My courses':profile.role==='tutor'?'My courses':'Platform users'} value={stats.primary} note="Active records" tone="blue"/><Metric label={profile.role==='student'?'Lessons completed':profile.role==='tutor'?'My students':'Active courses'} value={stats.secondary} note="Current workspace" tone="mint"/><Metric label="Classes completed" value={stats.tertiary} note="Recorded live sessions" tone="coral"/><Metric label="Skillvelop ID" value={profile.public_id?.split('-').at(-1)??'—'} note="Permanent member identity"/></div>
    <div className="form-page tutor-profile-layout"><section className="form-card"><form action="/api/lms" method="post" encType="multipart/form-data"><input type="hidden" name="action" value="update-profile"/><div className="profile-form-section"><span className="panel-kicker">BASIC INFORMATION</span><label className="photo-upload"><Camera size={22}/><span><strong>Profile picture</strong><small>JPG, PNG or WebP · maximum 4 MB</small></span><input type="file" name="avatar" accept="image/jpeg,image/png,image/webp"/></label><div className="form-row"><label>Full name<input value={profile.name} readOnly/></label><label>Email address<input value={profile.email} readOnly/></label></div><div className="form-row"><label>Phone number<input name="phone" defaultValue={details?.phone} placeholder="+91 98765 43210"/></label><label>Timezone<select name="timezone" defaultValue={details?.timezone??'Asia/Kolkata'}>{supportedTimeZones().map(zone=><option value={zone} key={zone}>{zone.replaceAll('_',' ')}</option>)}</select></label></div><label>Preferred language<select name="language" defaultValue={details?.preferred_language??'English'}><option>English</option><option>Hindi</option><option>Telugu</option><option>Tamil</option><option>Kannada</option></select></label><label>About me<textarea name="bio" rows={5} defaultValue={details?.bio} placeholder="Share your goals, interests or teaching introduction…"/></label></div>
      {profile.role==='tutor'&&<><div className="profile-form-section"><span className="panel-kicker">PUBLIC TUTOR IDENTITY</span><label>Professional headline<input name="headline" defaultValue={details?.headline} placeholder="e.g. Mathematics educator helping learners build confident problem-solving skills"/></label><label>Introduction video URL<input type="url" name="introVideoUrl" defaultValue={details?.intro_video_url} placeholder="https://youtube.com/watch?v=… or Vimeo URL"/></label><div className="form-row"><label>Location<input name="location" defaultValue={details?.location} placeholder="Hyderabad, India"/></label><label>Years of experience<input type="number" min="0" max="70" name="experienceYears" defaultValue={details?.experience_years??0}/></label></div><label>Subject areas<textarea name="subjectAreas" rows={2} defaultValue={details?.subject_areas||details?.specialties} placeholder="Mathematics, Physics, English…"/></label><label>Grades / levels taught<textarea name="gradeLevels" rows={2} defaultValue={details?.grade_levels} placeholder="Grades 6–10, GCSE, working professionals…"/></label><label>Teaching specialties<textarea name="specialties" rows={3} defaultValue={details?.specialties} placeholder="Algebra, Cambridge curriculum, SAT preparation…"/></label><label>Languages taught<textarea name="languages" rows={2} defaultValue={details?.languages} placeholder="English, Telugu, Hindi"/></label></div><div className="profile-form-section"><span className="panel-kicker">DIGITAL CV</span><label>Academic qualifications<textarea name="qualifications" rows={4} defaultValue={details?.qualifications} placeholder="Degrees, universities and relevant training…"/></label><label>Professional certifications<textarea name="certifications" rows={4} defaultValue={details?.certifications} placeholder="Teaching licences, subject certifications and professional credentials…"/></label><label>Achievements<textarea name="achievements" rows={4} defaultValue={details?.achievements} placeholder="Awards, milestones, publications and student outcomes…"/></label><label>Teaching philosophy<textarea name="teachingPhilosophy" rows={5} defaultValue={details?.teaching_philosophy} placeholder="Explain how you make live 1:1 learning effective and inclusive…"/></label><div className="form-row"><label>LinkedIn URL<input type="url" name="linkedinUrl" defaultValue={details?.linkedin_url} placeholder="https://linkedin.com/in/…"/></label><label>Website URL<input type="url" name="websiteUrl" defaultValue={details?.website_url} placeholder="https://…"/></label></div></div></>}<button>Save and update my profile →</button></form></section>
      <aside className="help-card profile-side-help"><BadgeCheck size={26}/><h3>{profile.role==='tutor'?"Your live digital CV":"Account identity"}</h3><p>{profile.role==='tutor'?"Every save refreshes your public tutor page on the main Skillvelop portal. Your permanent Skillvelop ID remains unchanged.":"Your name and email come from secure sign-in. Skillvelop stores only the profile preferences entered here."}</p>{publicHref&&<a className="module-link secondary" href={publicHref}>Preview public page →</a>}{profile.permissions?.length?<><h3>Manager permissions</h3><ul>{profile.permissions.map(p=><li key={p}>{p.replaceAll('_',' ')}</li>)}</ul></>:null}</aside>
    </div>
  </LmsShell>;
}
