import { all, first } from "@/db/lms";
import { LmsShell, Metric, Status, activityIcon, formatDate, initials } from "../components";
import { requireRole } from "../auth";
import DashboardInsights from "../DashboardInsights";
import { supportedTimeZones } from "@/db/timezones";
import { DateTimePicker12 } from "@/app/components/DateTimePicker12";

type Course = { id:string; title:string; subject:string; level:string; students:number };
type ClassItem = { id:string; title:string; starts_at:string; duration_minutes:number; meeting_url:string; status:string; course:string; student:string|null };
type Activity = { id:string; title:string; type:string; due_at:string; points:number; status:string; course:string; submissions:number };
type Submission = { id:string; response:string; submitted_at:string; status:string; activity:string; student:string; email:string; score:number|null };
type Student = { id:string; name:string; email:string; courses:number; avg_progress:number };

export const dynamic = "force-dynamic";
export default async function TutorDashboard() {
  const profile = await requireRole("tutor", "/dashboard/tutor");
  const tutorId = profile.role === "admin" ? "usr_demo_tutor" : profile.id;
  const timezone=(await first<{timezone:string}>("SELECT timezone FROM user_profiles WHERE user_id=?",tutorId))?.timezone??"Asia/Kolkata";
  const courses = await all<Course>(`SELECT c.id,c.title,c.subject,c.level,COUNT(e.id) AS students FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id WHERE c.tutor_id=? GROUP BY c.id ORDER BY c.created_at DESC`, tutorId);
  const classes = await all<ClassItem>(`SELECT l.id,l.title,l.starts_at,l.duration_minutes,l.meeting_url,l.status,c.title AS course,s.name AS student FROM live_classes l JOIN courses c ON c.id=l.course_id LEFT JOIN users s ON s.id=l.student_id WHERE l.tutor_id=? ORDER BY l.starts_at ASC`, tutorId);
  const activities = await all<Activity>(`SELECT a.id,a.title,a.type,a.due_at,a.points,a.status,c.title AS course,COUNT(s.id) AS submissions FROM activities a JOIN courses c ON c.id=a.course_id LEFT JOIN submissions s ON s.activity_id=a.id WHERE a.tutor_id=? GROUP BY a.id ORDER BY a.due_at ASC`, tutorId);
  const submissions = await all<Submission>(`SELECT s.id,s.response,s.submitted_at,s.status,s.score,a.title AS activity,u.name AS student,u.email FROM submissions s JOIN activities a ON a.id=s.activity_id JOIN users u ON u.id=s.student_id WHERE a.tutor_id=? ORDER BY s.submitted_at DESC LIMIT 8`, tutorId);
  const students = await all<Student>(`SELECT u.id,u.name,u.email,COUNT(e.course_id) AS courses,ROUND(AVG(e.progress)) AS avg_progress FROM users u JOIN enrollments e ON e.student_id=u.id JOIN courses c ON c.id=e.course_id WHERE c.tutor_id=? GROUP BY u.id ORDER BY u.name`, tutorId);
  const reviewCount = await first<{total:number}>(`SELECT COUNT(*) AS total FROM submissions s JOIN activities a ON a.id=s.activity_id WHERE a.tutor_id=? AND s.status='submitted'`, tutorId);
  const avgProgress=students.length?students.reduce((sum,item)=>sum+(item.avg_progress??0),0)/students.length:0,completedClasses=classes.filter(item=>item.status==='completed').length,reviewed=submissions.filter(item=>item.status==='reviewed').length,totalSubmissions=activities.reduce((sum,item)=>sum+item.submissions,0);

  return <LmsShell profile={profile} activeRole="tutor" eyebrow="Your teaching studio" title="Make every 1:1 class count." subtitle="Plan live sessions, assign meaningful work and give each learner focused feedback." actions={<div className="heading-actions"><details className="action-menu secondary"><summary>+ Schedule class</summary><form action="/api/lms" method="post" className="quick-form"><input type="hidden" name="action" value="schedule-class"/><h3>Schedule a live 1:1 class</h3><label>Course<select name="courseId" required>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Student<select name="studentId" required><option value="">Choose student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Class title<input name="title" required placeholder="e.g. Algebra problem solving"/></label><div className="form-row schedule-row"><DateTimePicker12 name="startsAt" label="Starts at" required/><label>Minutes<input name="duration" type="number" min="15" max="180" defaultValue="60"/></label></div><label>Timezone<select name="timeZone" defaultValue={timezone}>{supportedTimeZones().map(zone=><option value={zone} key={zone}>{zone.replaceAll('_',' ')}</option>)}</select></label><label>Meeting link <span className="required-label">Required</span><input name="meetingUrl" type="url" inputMode="url" required placeholder="https://meet.google.com/..."/></label><button>Schedule class <span>→</span></button></form></details><details className="action-menu"><summary>+ Assign work</summary><form action="/api/lms" method="post" className="quick-form"><input type="hidden" name="action" value="create-activity"/><h3>Create learner work</h3><label>Course<select name="courseId" required>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Work type<select name="type"><option value="homework">Homework</option><option value="quiz">Quiz</option><option value="assessment">Assessment</option><option value="assignment">Assignment</option><option value="classwork">Class work</option></select></label><label>Title<input name="title" required placeholder="What should the learner complete?"/></label><label>Instructions<textarea name="instructions" required rows={3} placeholder="Clear instructions and success criteria"/></label><div className="form-row schedule-row"><DateTimePicker12 name="dueAt" label="Due date" required/><label>Points<input name="points" type="number" min="1" defaultValue="100"/></label></div><button>Publish to learner <span>→</span></button></form></details></div>}>
    <div className="metrics-grid"><Metric label="My learners" value={students.length} note="Across active courses"/><Metric label="Upcoming classes" value={classes.filter(c=>c.status==='scheduled').length} note="Live 1:1 sessions" tone="blue"/><Metric label="Awaiting review" value={reviewCount?.total ?? 0} note="Give timely feedback" tone="coral"/><Metric label="Learning activities" value={activities.length} note="Homework, quizzes & more" tone="mint"/></div>
    <DashboardInsights eyebrow="TEACHING INTELLIGENCE" title="Your learner impact" subtitle="A balanced view of progress, attendance, feedback and course activity across your current 1:1 learners." axes={[{label:"Progress",value:avgProgress},{label:"Attendance",value:classes.length?(completedClasses/classes.length)*100:0},{label:"Feedback",value:submissions.length?(reviewed/submissions.length)*100:100},{label:"Work",value:activities.length?Math.min(100,(totalSubmissions/activities.length)*25):0},{label:"Course reach",value:courses.length?Math.min(100,(students.length/courses.length)*30):0}]} donutValue={classes.length?(completedClasses/classes.length)*100:0} donutLabel="Class completion" donutNote={`${completedClasses} of ${classes.length} recorded classes have been delivered.`} trend={students.length?students.map(item=>item.avg_progress??0):[18,31,46,54,66,74]}/>
    <div className="dashboard-grid tutor-grid">
      <section className="panel span-2" id="classes"><div className="panel-head"><div><span className="panel-kicker">LIVE TEACHING · {timezone}</span><h2>Class schedule</h2></div><Status>{classes.filter(c=>c.status==='scheduled').length} upcoming</Status></div><div className="class-list">{classes.map(item=><article className="class-row" key={item.id}><div className="class-time"><strong>{new Intl.DateTimeFormat("en-IN",{timeZone:timezone,hour:"numeric",minute:"2-digit"}).format(new Date(item.starts_at))}</strong><span>{new Intl.DateTimeFormat("en-IN",{timeZone:timezone,weekday:"short",day:"numeric",month:"short"}).format(new Date(item.starts_at))}</span></div><div className="class-accent"/><div className="class-detail"><span>{item.course}</span><h3>{item.title}</h3><p>1:1 with {item.student ?? "course learners"} · {item.duration_minutes} minutes</p></div>{item.meeting_url ? <a className="join-button" href={item.meeting_url}>Open room ↗</a> : <Status tone="amber">Link needed</Status>}</article>)}</div></section>
      <section className="panel" id="students"><div className="panel-head"><div><span className="panel-kicker">LEARNERS</span><h2>Student pulse</h2></div></div><div className="student-list">{students.map(student=><article key={student.id}><span>{initials(student.name)}</span><div><strong>{student.name}</strong><small>{student.courses} course · {student.avg_progress ?? 0}% progress</small></div><i style={{"--progress":`${student.avg_progress ?? 0}%`} as React.CSSProperties}/></article>)}</div></section>
      <section className="panel span-2" id="work"><div className="panel-head"><div><span className="panel-kicker">LEARNING WORK</span><h2>Assignments & assessments</h2></div></div><div className="activity-list">{activities.map(item=><article key={item.id}><span className={`activity-symbol ${item.type}`}>{activityIcon(item.type)}</span><div><small>{item.type} · {item.course}</small><strong>{item.title}</strong><span>Due {formatDate(item.due_at)} · {item.points} points</span></div><div className="submission-count"><strong>{item.submissions}</strong><small>submitted</small></div></article>)}</div></section>
      <section className="panel"><div className="panel-head"><div><span className="panel-kicker">TO REVIEW</span><h2>Latest submissions</h2></div></div><div className="review-list">{submissions.length ? submissions.map(item=><details key={item.id}><summary><span>{initials(item.student)}</span><div><strong>{item.student}</strong><small>{item.activity}</small></div><Status tone={item.status==='reviewed'?'green':'amber'}>{item.status}</Status></summary><div className="review-body"><p>{item.response}</p><form action="/api/lms" method="post"><input type="hidden" name="action" value="review-submission"/><input type="hidden" name="submissionId" value={item.id}/><label>Score<input name="score" type="number" min="0" max="100" defaultValue={item.score ?? 80}/></label><label>Feedback<textarea name="feedback" rows={2} required placeholder="Actionable learner feedback"/></label><button>Return feedback</button></form></div></details>) : <div className="empty-state"><span>✓</span><strong>All caught up</strong><p>New learner submissions will appear here.</p></div>}</div></section>
    </div>
  </LmsShell>;
}

