import { createId, database } from "@/db/lms";
import { validTimeZone, zonedLocalToUtc } from "@/db/timezones";
import { NextResponse } from "next/server";

function value(form:FormData,name:string){return String(form.get(name)??"").trim();}
const dayIndex:Record<string,number>={Sun:0,Mon:1,Tue:2,Wed:3,Thu:4,Fri:5,Sat:6};
function localSlotMoment(moment:Date,timeZone:string){const parts=new Intl.DateTimeFormat("en-US",{timeZone,weekday:"short",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(moment),part=(type:string)=>parts.find(item=>item.type===type)?.value??"";return {weekday:dayIndex[part("weekday")],minutes:Number(part("hour"))*60+Number(part("minute"))};}

export async function POST(request:Request){
  const form=await request.formData();if(value(form,"website"))return NextResponse.redirect(new URL("/book-demo?submitted=1",request.url),303);
  const studentName=value(form,"studentName").slice(0,160),guardianName=value(form,"guardianName").slice(0,160),email=value(form,"email").toLowerCase().slice(0,200),phone=value(form,"phone").slice(0,50),timeZone=value(form,"timeZone"),curriculumId=value(form,"curriculumId"),subjectId=value(form,"subjectId"),grade=value(form,"grade").slice(0,100),tutorId=value(form,"tutorId"),startsAt=value(form,"startsAt"),notes=value(form,"notes").slice(0,2000);
  if(!studentName||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||validTimeZone(timeZone)!==timeZone||!curriculumId||!subjectId||!grade||!tutorId||!startsAt)return NextResponse.redirect(new URL("/book-demo?error=required",request.url),303);
  const startsAtUtc=zonedLocalToUtc(startsAt,timeZone);if(!startsAtUtc)return NextResponse.redirect(new URL("/book-demo?error=time",request.url),303);const starts=new Date(startsAtUtc);if(starts.getTime()<Date.now()+2*60*60*1000)return NextResponse.redirect(new URL("/book-demo?error=time",request.url),303);
  const db=database(),subject=await db.prepare("SELECT cs.grades_json FROM curriculum_subjects cs JOIN curricula c ON c.id=cs.curriculum_id WHERE cs.id=? AND cs.curriculum_id=? AND cs.status='active' AND c.status='active'").bind(subjectId,curriculumId).first<{grades_json:string}>();let grades:string[]=[];try{grades=JSON.parse(subject?.grades_json??"[]")as string[];}catch{grades=[];}const slots=await db.prepare("SELECT weekday,start_minutes,end_minutes,timezone FROM tutor_availability_slots WHERE tutor_id=? AND is_open=1").bind(tutorId).all<{weekday:number;start_minutes:number;end_minutes:number;timezone:string}>();const available=slots.results.some(slot=>{const local=localSlotMoment(starts,slot.timezone);return local.weekday===slot.weekday&&local.minutes>=slot.start_minutes&&local.minutes+30<=slot.end_minutes;});if(!subject||!grades.includes(grade)||!available)return NextResponse.redirect(new URL("/book-demo?error=slot",request.url),303);
  const code=`DEMO-${crypto.randomUUID().slice(0,8).toUpperCase()}`;await db.prepare("INSERT INTO demo_bookings (id,public_code,student_name,guardian_name,email,phone,timezone,curriculum_id,subject_id,grade_level,tutor_id,starts_at,duration_minutes,notes,status,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,30,?,'requested',?)").bind(createId("dmo"),code,studentName,guardianName,email,phone,timeZone,curriculumId,subjectId,grade,tutorId,starts.toISOString(),notes,new Date().toISOString()).run();return NextResponse.redirect(new URL(`/book-demo?submitted=1&reference=${encodeURIComponent(code)}`,request.url),303);
}
