import { all, first } from "@/db/lms";
import { LmsShell, Metric, Status, formatDate, initials } from "../components";
import { requireAdminPermission } from "../auth";
import DashboardInsights from "../DashboardInsights";

type Totals = { users: number; tutors: number; students: number; courses: number };
type UserRow = { id: string; name: string; email: string; role: string; status: string; created_at: string };
type CourseRow = { id: string; title: string; subject: string; level: string; status: string; tutor: string | null; students: number };
type ClassRow = { id: string; title: string; starts_at: string; duration_minutes: number; course: string; tutor: string; student: string | null; status: string };
type SafetyAlert={id:string;sender:string;recipient:string;course:string|null;blocked_body:string;reasons_json:string;created_at:string};

export const dynamic = "force-dynamic";
export default async function AdminDashboard() {
  const profile = await requireAdminPermission("view_dashboard", "/dashboard/admin");
  const totals = await first<Totals>(`SELECT COUNT(*) AS users, SUM(CASE WHEN role='tutor' THEN 1 ELSE 0 END) AS tutors, SUM(CASE WHEN role='student' THEN 1 ELSE 0 END) AS students, (SELECT COUNT(*) FROM courses WHERE status!='archived') AS courses FROM users`);
  const users = await all<UserRow>("SELECT id, name, email, role, status, created_at FROM users ORDER BY created_at DESC LIMIT 10");
  const courses = await all<CourseRow>(`SELECT c.id, c.title, c.subject, c.level, c.status, u.name AS tutor, COUNT(e.id) AS students FROM courses c LEFT JOIN users u ON u.id=c.tutor_id LEFT JOIN enrollments e ON e.course_id=c.id GROUP BY c.id ORDER BY c.created_at DESC`);
  const classes = await all<ClassRow>(`SELECT l.id,l.title,l.starts_at,l.duration_minutes,l.status,c.title AS course,t.name AS tutor,s.name AS student FROM live_classes l JOIN courses c ON c.id=l.course_id JOIN users t ON t.id=l.tutor_id LEFT JOIN users s ON s.id=l.student_id ORDER BY l.starts_at ASC LIMIT 6`);
  const pending = await first<{ total: number }>("SELECT COUNT(*) AS total FROM submissions WHERE status='submitted'");
  const safetyAlerts=await all<SafetyAlert>(`SELECT a.id,s.name sender,r.name recipient,c.title course,a.blocked_body,a.reasons_json,a.created_at FROM chat_moderation_alerts a JOIN users s ON s.id=a.sender_id JOIN users r ON r.id=a.recipient_id LEFT JOIN courses c ON c.id=a.course_id WHERE a.status='open' ORDER BY a.created_at DESC LIMIT 8`);
  const insight=await first<{avg_progress:number;all_classes:number;completed_classes:number;all_submissions:number;reviewed_submissions:number;paid_students:number}>(`SELECT COALESCE(ROUND((SELECT AVG(progress) FROM enrollments)),0) avg_progress,(SELECT COUNT(*) FROM live_classes) all_classes,(SELECT COUNT(*) FROM live_classes WHERE status='completed') completed_classes,(SELECT COUNT(*) FROM submissions) all_submissions,(SELECT COUNT(*) FROM submissions WHERE status='reviewed') reviewed_submissions,(SELECT COUNT(*) FROM student_subscriptions WHERE plan_type='paid') paid_students`);

  return <LmsShell profile={profile} activeRole="admin" eyebrow="Operations command centre" title="Good to see you, Admin." subtitle="Manage people, learning programmes and every live 1:1 class from one place." actions={<div className="heading-actions"><a className="primary-action" href="/dashboard/admin/courses/new">+ Create course</a><details className="action-menu"><summary>+ Create user</summary><form action="/api/lms" method="post" className="quick-form"><input type="hidden" name="action" value="create-user"/><h3>Create a Skillvelop user</h3><label>Full name<input name="name" required placeholder="e.g. Neha Sharma" /></label><label>Email<input type="email" name="email" required placeholder="name@example.com" /></label><label>Role<select name="role" defaultValue="student"><option value="student">Student</option><option value="tutor">Tutor</option><option value="admin">Admin</option></select></label><button type="submit">Create & invite <span>→</span></button></form></details></div>}>
    <div className="metrics-grid"><Metric label="Total users" value={totals?.users ?? 0} note="Across all roles"/><Metric label="Active tutors" value={totals?.tutors ?? 0} note="Available for 1:1 learning" tone="blue"/><Metric label="Students" value={totals?.students ?? 0} note="Enrolled learners" tone="mint"/><Metric label="Live courses" value={totals?.courses ?? 0} note={`${pending?.total ?? 0} submissions await review`} tone="coral"/></div>
    <DashboardInsights eyebrow="ACADEMY INTELLIGENCE" title="Platform health at a glance" subtitle="See where learning, delivery and learner operations need attention without opening separate reports." axes={[{label:"Learner progress",value:insight?.avg_progress??0},{label:"Class delivery",value:insight?.all_classes?((insight.completed_classes/insight.all_classes)*100):0},{label:"Review speed",value:insight?.all_submissions?((insight.reviewed_submissions/insight.all_submissions)*100):100},{label:"Paid access",value:totals?.students?(((insight?.paid_students??0)/totals.students)*100):0},{label:"Tutor coverage",value:totals?.courses?Math.min(100,((totals?.tutors??0)/totals.courses)*100):0}]} donutValue={insight?.all_classes?((insight.completed_classes/insight.all_classes)*100):0} donutLabel="Classes delivered" donutNote={`${insight?.completed_classes??0} of ${insight?.all_classes??0} recorded sessions are complete.`} trend={[32,48,41,58,64,70,76,82]}/>
    <div className="dashboard-grid admin-grid">
      {safetyAlerts.length?<section className="panel span-3 safety-alert-panel"><div className="panel-head"><div><span className="panel-kicker">SAFEGUARDING</span><h2>Blocked contact-sharing attempts</h2></div><Status tone="amber">{safetyAlerts.length} open</Status></div><div>{safetyAlerts.map(alert=><article key={alert.id}><div><strong>{alert.sender} → {alert.recipient}</strong><small>{alert.course??"Direct learning conversation"} · {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(alert.created_at))}</small></div><p>{alert.blocked_body}</p><span>{(JSON.parse(alert.reasons_json)as string[]).join(" · ")}</span></article>)}</div></section>:null}
      <section className="panel span-2" id="users"><div className="panel-head"><div><span className="panel-kicker">PEOPLE</span><h2>Users & access</h2></div><span className="subtle-link">Role-managed access</span></div><div className="data-table"><div className="table-row table-head"><span>User</span><span>Role</span><span>Status</span><span>Joined</span></div>{users.map((user) => <div className="table-row" key={user.id}><span className="person-cell"><i>{initials(user.name)}</i><b>{user.name}<small>{user.email}</small></b></span><span className="role-label">{user.role}</span><span><Status tone={user.status === "active" ? "green" : "amber"}>{user.status}</Status></span><span className="muted">{new Date(user.created_at).toLocaleDateString("en-IN", { day:"numeric", month:"short", year:"numeric" })}</span></div>)}</div></section>
      <section className="panel" id="classes"><div className="panel-head"><div><span className="panel-kicker">SCHEDULE</span><h2>Upcoming classes</h2></div></div><div className="timeline-list">{classes.map((item) => <article className="timeline-item" key={item.id}><div className="date-box"><strong>{new Date(item.starts_at).getDate()}</strong><span>{new Date(item.starts_at).toLocaleDateString("en-IN", { month:"short" })}</span></div><div><strong>{item.title}</strong><span>{formatDate(item.starts_at)} · {item.duration_minutes} min</span><small>{item.tutor} with {item.student ?? "Open learner"}</small></div></article>)}</div></section>
      <section className="panel span-3" id="courses"><div className="panel-head"><div><span className="panel-kicker">PROGRAMMES</span><h2>Course portfolio</h2></div><a className="subtle-link" href="/dashboard/tutor">Open teaching view →</a></div><div className="course-admin-grid">{courses.map((course) => <article className="admin-course" key={course.id}><span className="course-symbol">{course.subject.slice(0,2).toUpperCase()}</span><div><Status>{course.status}</Status><h3>{course.title}</h3><p>{course.level} · {course.tutor ?? "Tutor unassigned"}</p><small>{course.students} learner{course.students === 1 ? "" : "s"} enrolled</small></div></article>)}</div></section>
    </div>
  </LmsShell>;
}
