import { all, first } from "@/db/lms";
import { LmsShell, Metric, Status } from "../../components";
import { requireRole } from "../../auth";

type CourseReport={title:string;progress:number;lessons_done:number;quiz_attempts:number;average_score:number|null;work_submitted:number};
export const dynamic="force-dynamic";
export default async function Page(){
  const profile=await requireRole("student","/dashboard/student/reports"); const studentId=profile.role==='admin'?'usr_demo_student':profile.id;
  const month=new Date().toISOString().slice(0,7);
  const courses=await all<CourseReport>(`SELECT c.title,e.progress,(SELECT COUNT(*) FROM lesson_progress lp JOIN lessons l ON l.id=lp.lesson_id WHERE lp.student_id=e.student_id AND l.course_id=c.id AND substr(lp.completed_at,1,7)=?) lessons_done,(SELECT COUNT(*) FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.student_id=e.student_id AND q.course_id=c.id AND substr(qa.submitted_at,1,7)=?) quiz_attempts,(SELECT ROUND(AVG(CASE WHEN qa.max_score>0 THEN qa.score*100.0/qa.max_score END)) FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id WHERE qa.student_id=e.student_id AND q.course_id=c.id AND substr(qa.submitted_at,1,7)=?) average_score,(SELECT COUNT(*) FROM submissions s JOIN activities a ON a.id=s.activity_id WHERE s.student_id=e.student_id AND a.course_id=c.id AND substr(s.submitted_at,1,7)=?) work_submitted FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE e.student_id=? ORDER BY c.title`,month,month,month,month,studentId);
  const classes=await first<{total:number}>("SELECT COUNT(*) total FROM live_classes WHERE (student_id=? OR (student_id IS NULL AND course_id IN (SELECT course_id FROM enrollments WHERE student_id=?))) AND status='completed' AND substr(starts_at,1,7)=?",studentId,studentId,month);
  const game=await first<{xp:number;level:number;streak_days:number}>("SELECT xp,level,streak_days FROM student_gamification WHERE student_id=?",studentId);
  const avg=courses.length?Math.round(courses.reduce((sum,c)=>sum+(c.progress||0),0)/courses.length):0;
  return <LmsShell profile={profile} activeRole="student" activePath="/dashboard/student/reports" eyebrow="Learning analytics" title="Monthly progress report" subtitle={`Your activity, achievement and course progress for ${new Date().toLocaleDateString('en-IN',{month:'long',year:'numeric'})}.`}><div className="metrics-grid"><Metric label="Current level" value={game?.level??1} note={`${game?.xp??0} total XP`} tone="blue"/><Metric label="Course progress" value={`${avg}%`} note="Average across enrolled courses" tone="mint"/><Metric label="Classes completed" value={classes?.total??0} note="This month" tone="coral"/><Metric label="Learning streak" value={`${game?.streak_days??0} days`} note="Keep showing up"/></div><section className="panel"><div className="panel-head"><div><span className="panel-kicker">COURSE BREAKDOWN</span><h2>This month at a glance</h2></div><Status>{courses.length} courses</Status></div><div className="report-grid">{courses.map(course=><article key={course.title}><h3>{course.title}</h3><div className="report-progress"><span style={{width:`${course.progress}%`}}/></div><strong>{course.progress}% overall</strong><dl><div><dt>Lessons finished</dt><dd>{course.lessons_done}</dd></div><div><dt>Quiz attempts</dt><dd>{course.quiz_attempts}</dd></div><div><dt>Average quiz score</dt><dd>{course.average_score===null?'—':`${course.average_score}%`}</dd></div><div><dt>Work submitted</dt><dd>{course.work_submitted}</dd></div></dl></article>)}</div></section></LmsShell>;
}
