import { all, first } from "@/db/lms";
import { LmsShell, Notice, Status, formatDate } from "../../../components";
import { requireAdminPermission } from "../../../auth";
import { notFound } from "next/navigation";

type Student={id:string;name:string;email:string;status:string}; type Subscription={id:string;plan_type:string;class_allowance:number;months_purchased:number;started_at:string;expires_at:string;renewal_count:number;notes:string}; type Enrolment={id:string;title:string;subject:string;level:string;progress:number;tutor:string|null;created_at:string}; type Renewal={id:string;added_classes:number;added_months:number;previous_expiry:string;new_expiry:string;created_at:string;manager:string};
export const dynamic="force-dynamic";

export default async function Page({params,searchParams}:{params:Promise<{id:string}>;searchParams:Promise<Record<string,string|undefined>>}){
  const {id}=await params; const profile=await requireAdminPermission("manage_students",`/dashboard/admin/students/${id}`);
  const student=await first<Student>("SELECT id,name,email,status FROM users WHERE id=? AND role='student'",id); if(!student) notFound();
  const subscription=await first<Subscription>("SELECT * FROM student_subscriptions WHERE student_id=?",id);
  const used=await first<{total:number}>("SELECT COUNT(*) total FROM live_classes WHERE student_id=? AND status='completed' AND starts_at>=?",id,subscription?.started_at??"1970-01-01");
  const enrolments=await all<Enrolment>(`SELECT e.id,c.title,c.subject,c.level,e.progress,u.name tutor,e.created_at FROM enrollments e JOIN courses c ON c.id=e.course_id LEFT JOIN users u ON u.id=c.tutor_id WHERE e.student_id=? ORDER BY e.created_at DESC`,id);
  const renewals=subscription?await all<Renewal>(`SELECT r.id,r.added_classes,r.added_months,r.previous_expiry,r.new_expiry,r.created_at,u.name manager FROM subscription_renewals r JOIN users u ON u.id=r.created_by WHERE r.subscription_id=? ORDER BY r.created_at DESC`,subscription.id):[];
  const remaining=Math.max(0,(subscription?.class_allowance??0)-(used?.total??0));
  return <LmsShell profile={profile} activeRole="admin" activePath="/dashboard/admin/students" eyebrow="Student account" title={student.name} subtitle={`${student.email} · Manage enrolment and commercial access.`} actions={<a className="module-link secondary" href="/dashboard/admin/students">← All students</a>}>
    <Notice params={await searchParams}/><div className="metrics-grid"><article className="metric-card"><span>PLAN</span><strong className="metric-word">{subscription?.plan_type??'Not set'}</strong><small>{subscription?`Since ${new Date(subscription.started_at).toLocaleDateString('en-IN')}`:'Add a plan below'}</small></article><article className="metric-card blue"><span>CLASS BALANCE</span><strong>{remaining}</strong><small>{used?.total??0} used of {subscription?.class_allowance??0}</small></article><article className="metric-card mint"><span>COURSES</span><strong>{enrolments.length}</strong><small>Active enrolment records</small></article><article className="metric-card coral"><span>VALID UNTIL</span><strong className="metric-date">{subscription?new Date(subscription.expires_at).toLocaleDateString('en-IN',{day:'numeric',month:'short'}):'—'}</strong><small>{subscription?.months_purchased??0} months purchased</small></article></div>
    <div className="student-detail-grid"><section className="panel"><div className="panel-head"><div><span className="panel-kicker">COURSE ENROLMENT</span><h2>Learning programmes</h2></div></div>{enrolments.length?enrolments.map(e=><article className="enrolment-row" key={e.id}><div><h3>{e.title}</h3><p>{e.subject} · {e.level} · Tutor: {e.tutor??'Unassigned'}</p><small>Enrolled {new Date(e.created_at).toLocaleDateString('en-IN')}</small></div><div><Status>{e.progress}% complete</Status><div className="mini-progress"><i style={{width:`${e.progress}%`}}/></div></div></article>):<div className="empty-module"><h3>No courses yet</h3><p>Enrol this learner while creating or editing a course.</p></div>}</section>
      <section className="panel"><div className="panel-head"><div><span className="panel-kicker">PLAN SETTINGS</span><h2>{subscription?'Update access':'Set trial or paid access'}</h2></div></div><form className="inline-admin-form" action="/api/lms" method="post"><input type="hidden" name="action" value="update-subscription"/><input type="hidden" name="studentId" value={id}/><label>Plan type<select name="planType" defaultValue={subscription?.plan_type??'trial'}><option value="trial">Trial</option><option value="paid">Paid</option></select></label><div className="form-row"><label>Total classes<input name="classAllowance" type="number" min="1" max="1000" defaultValue={subscription?.class_allowance??1}/></label><label>Purchased months<input name="months" type="number" min="0" max="60" defaultValue={subscription?.months_purchased??0}/></label></div><label>Admin notes<textarea name="notes" rows={3} defaultValue={subscription?.notes}/></label><button>Save plan</button></form>{subscription&&<><div className="panel-divider"/><h3>Renew subscription</h3><form className="inline-admin-form renewal-form" action="/api/lms" method="post"><input type="hidden" name="action" value="renew-subscription"/><input type="hidden" name="studentId" value={id}/><div className="form-row"><label>Add classes<input name="addedClasses" type="number" min="1" defaultValue="8"/></label><label>Add months<input name="addedMonths" type="number" min="1" defaultValue="1"/></label></div><button>Renew & extend →</button></form></>}</section>
      <section className="panel span-2"><div className="panel-head"><div><span className="panel-kicker">RENEWAL HISTORY</span><h2>Commercial timeline</h2></div></div>{renewals.length?<div className="timeline-list">{renewals.map(r=><article className="renewal-row" key={r.id}><Status>Renewed</Status><div><strong>+{r.added_classes} classes · +{r.added_months} month{r.added_months===1?'':'s'}</strong><p>{new Date(r.previous_expiry).toLocaleDateString('en-IN')} → {new Date(r.new_expiry).toLocaleDateString('en-IN')}</p></div><small>{formatDate(r.created_at)} by {r.manager}</small></article>)}</div>:<div className="empty-module"><h3>No renewals yet</h3><p>Every renewal will be recorded here.</p></div>}</section>
    </div>
  </LmsShell>;
}
