import { all, first } from "@/db/lms";
import { notFound } from "next/navigation";
import { BookOpen, CheckCircle2, ChevronDown, ClipboardList, FileQuestion, LockKeyhole } from "lucide-react";
import { LmsShell, Status, formatDate } from "../../../components";
import { requireRole } from "../../../auth";
import CourseAIFloat from "../../../CourseAIFloat";
import { hasStoredCredential } from "@/app/api/ai/provider";
import { learningItemHref, loadLearningSequence } from "@/db/learning-sequence";
import Link from "next/link";

type Course={id:string;title:string;subject:string;level:string;description:string;cover_image_url:string;is_unlocked:number;progress:number};
type Chapter={id:string;title:string;description:string;position:number;is_unlocked:number};
type Lesson={id:string;chapter_id:string|null;title:string;summary:string;position:number;duration_minutes:number;is_unlocked:number;completed_at:string|null};
type Quiz={id:string;chapter_id:string|null;title:string;description:string;kind:string;is_unlocked:number;attempts:number};
type Activity={id:string;chapter_id:string|null;title:string;type:string;due_at:string;points:number;submitted:number;is_unlocked:number};
export const dynamic="force-dynamic";

export default async function CourseOverview({params}:{params:Promise<{courseId:string}>}){
  const profile=await requireRole("student","/dashboard/student/curriculum");const studentId=profile.role==='admin'?'usr_demo_student':profile.id;const {courseId}=await params;
  const course=await first<Course>(`SELECT c.id,c.title,c.subject,c.level,c.description,c.cover_image_url,c.is_unlocked,e.progress FROM courses c JOIN enrollments e ON e.course_id=c.id AND e.student_id=? WHERE c.id=? AND c.status='active'`,studentId,courseId);if(!course||!course.is_unlocked)notFound();
  const chapters=await all<Chapter>("SELECT id,title,description,position,is_unlocked FROM chapters WHERE course_id=? ORDER BY position",courseId);
  const lessons=await all<Lesson>(`SELECT l.id,l.chapter_id,l.title,l.summary,l.position,l.duration_minutes,l.is_unlocked,lp.completed_at FROM lessons l LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.student_id=? WHERE l.course_id=? AND l.status='published' ORDER BY l.chapter_id,l.position`,studentId,courseId);
  const quizzes=await all<Quiz>(`SELECT q.id,q.chapter_id,q.title,q.description,q.kind,q.is_unlocked,COUNT(qa.id) attempts FROM quizzes q LEFT JOIN quiz_attempts qa ON qa.quiz_id=q.id AND qa.student_id=? WHERE q.course_id=? AND q.status='published' GROUP BY q.id ORDER BY q.chapter_id,q.created_at`,studentId,courseId);
  const activities=await all<Activity>(`SELECT a.id,a.chapter_id,a.title,a.type,a.due_at,a.points,a.is_unlocked,CASE WHEN s.id IS NULL THEN 0 ELSE 1 END submitted FROM activities a LEFT JOIN submissions s ON s.activity_id=a.id AND s.student_id=? WHERE a.course_id=? AND a.status='published' ORDER BY a.chapter_id,a.due_at`,studentId,courseId);
  const sequence=await loadLearningSequence(courseId,studentId);
  const plan=await first<{plan_type:string;expires_at:string}>("SELECT plan_type,expires_at FROM student_subscriptions WHERE student_id=?",studentId),ai=await first<{provider:"openai"|"anthropic";enabled:number}>("SELECT provider,enabled FROM ai_settings WHERE id='platform'");const assistantEnabled=Boolean(plan?.plan_type==='paid'&&plan.expires_at>new Date().toISOString()&&ai?.enabled&&await hasStoredCredential(ai.provider));
  return <LmsShell profile={profile} activeRole="student" activePath="/dashboard/student/curriculum" eyebrow={`${course.subject} · ${course.level}`} title={course.title} subtitle={course.description} actions={<Link className="module-link secondary" href="/dashboard/student/curriculum">← All courses</Link>}>
    <section className="course-overview-hero"><div><span>YOUR COURSE PATH</span><h2>Learn one chapter at a time</h2><p>Open each released chapter to access its lessons, quizzes, assignments and assessments.</p></div><div className="course-progress-ring" style={{background:`conic-gradient(#ff7168 ${course.progress * 3.6}deg,rgba(255,255,255,.16) 0deg)`}}><span><strong>{course.progress}%</strong><small>complete</small></span></div></section>
    <div className="chapter-card-grid">{chapters.map(chapter=>{const open=Boolean(chapter.is_unlocked);const chapterLessons=lessons.filter(item=>item.chapter_id===chapter.id);const chapterQuizzes=quizzes.filter(item=>item.chapter_id===chapter.id);const chapterActivities=activities.filter(item=>item.chapter_id===chapter.id);const chapterSequence=sequence.filter(item=>item.chapterId===chapter.id);const total=chapterLessons.length+chapterQuizzes.length+chapterActivities.length;const completed=chapterLessons.filter(item=>item.completed_at).length+chapterQuizzes.filter(item=>item.attempts>0).length+chapterActivities.filter(item=>item.submitted).length;const progress=total?Math.round(completed/total*100):0;return <details className={open?"chapter-card":"chapter-card locked"} open={open&&chapter.position===1} key={chapter.id}>
      <summary><div className="chapter-number">{chapter.position}</div><div><span>CHAPTER {chapter.position}</span><h2>{chapter.title}</h2><p>{chapter.description||"Your tutor is preparing the chapter overview."}</p><small className="chapter-summary-counts">{chapterLessons.length} lessons · {chapterQuizzes.length} quizzes/assessments · {chapterActivities.length} assignments</small></div><div className="chapter-summary-end"><div className="chapter-progress-ring" style={{background:`conic-gradient(#7464d8 ${progress * 3.6}deg,#e9e8ee 0deg)`}}><span><strong>{progress}%</strong><small>{completed}/{total}</small></span></div><span className="chapter-toggle"><ChevronDown size={16}/><b/></span></div></summary>
      {!open?<div className="chapter-locked-message"><LockKeyhole size={20}/><div><strong>Chapter locked</strong><p>Your tutor will release this chapter when you are ready.</p></div></div>:<div className="chapter-content-list">
        {chapterSequence.map(item=>{const lesson=item.type==='lesson'?chapterLessons.find(row=>row.id===item.id):null,quiz=item.type==='quiz'?chapterQuizzes.find(row=>row.id===item.id):null,activity=item.type==='activity'?chapterActivities.find(row=>row.id===item.id):null;const icon=item.type==='lesson'?<BookOpen size={18}/>:item.type==='quiz'?<FileQuestion size={18}/>:<ClipboardList size={18}/>;const meta=lesson?`LESSON ${lesson.position} · ${lesson.duration_minutes} MIN`:quiz?quiz.kind.replaceAll('_',' '):activity?`${activity.type} · DUE ${formatDate(activity.due_at)}`:item.label;const status=item.completed?'Completed':item.available?'Open in player →':item.tutorUnlocked?'Complete previous step':'Tutor locked';return item.available?<a href={learningItemHref(item)} key={`${item.type}-${item.id}`}><i className={`content-icon ${item.type==='activity'?'work':item.type}`}>{item.completed?<CheckCircle2 size={18}/>:icon}</i><div><span>{meta}</span><strong>{item.title}</strong><p>{item.summary}</p></div><b>{status}</b></a>:<div className="content-row locked" key={`${item.type}-${item.id}`}><i className="content-icon"><LockKeyhole size={17}/></i><div><span>{meta}</span><strong>{item.title}</strong></div><b>{status}</b></div>})}
        {!total&&<div className="chapter-empty"><BookOpen size={22}/><p>Your tutor is preparing the learning items for this chapter.</p></div>}
      </div>}
      <footer><Status tone={open?'green':'amber'}>{open?'Available now':'Coming soon'}</Status><span>{chapterLessons.length} lessons · {chapterQuizzes.length} quizzes/assessments · {chapterActivities.length} assignments</span></footer>
    </details>})}{!chapters.length&&<div className="panel empty-module"><h3>Your first chapter is being prepared</h3><p>It will appear here as soon as your tutor publishes it.</p></div>}</div>{assistantEnabled&&<CourseAIFloat courseId={course.id} contextLabel={`${course.title} course`}/>}
  </LmsShell>;
}
