import { all, first } from "@/db/lms";
import { dateKeyInTimeZone } from "@/db/timezones";
import { LmsShell, Metric, Notice, Status, formatDate } from "../../components";
import { requireRole } from "../../auth";

type Row={id:string;title:string;starts_at:string;duration_minutes:number;meeting_url:string;notes:string;course:string;tutor:string;status:string;student_rating:number|null};
type Entitlement={plan_type:string;class_allowance:number;expires_at:string};
export const dynamic="force-dynamic";

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole("student","/dashboard/student/classes"),id=profile.role==='admin'?'usr_demo_student':profile.id,now=new Date().toISOString();
  const timezone=(await first<{timezone:string}>("SELECT timezone FROM user_profiles WHERE user_id=?",id))?.timezone??"Asia/Kolkata";
  const rows=await all<Row>(`SELECT l.id,l.title,l.starts_at,l.duration_minutes,l.meeting_url,l.notes,l.status,l.student_rating,c.title course,u.name tutor FROM live_classes l JOIN courses c ON c.id=l.course_id JOIN users u ON u.id=l.tutor_id WHERE (l.student_id=? OR (l.student_id IS NULL AND l.course_id IN (SELECT course_id FROM enrollments WHERE student_id=?))) AND l.status!='cancelled' ORDER BY l.starts_at`,id,id);
  const upcoming=rows.filter(row=>row.status==='scheduled'&&row.starts_at>now),pending=rows.filter(row=>row.status==='awaiting_confirmation');
  const entitlement=await first<Entitlement>("SELECT plan_type,class_allowance,expires_at FROM student_subscriptions WHERE student_id=?",id);
  const used=await first<{total:number}>("SELECT COUNT(DISTINCT id) total FROM live_classes WHERE (student_id=? OR (student_id IS NULL AND course_id IN (SELECT course_id FROM enrollments WHERE student_id=?))) AND status='completed'",id,id);
  const taken=used?.total??0,remaining=Math.max(0,(entitlement?.class_allowance??0)-taken),today=new Date();const days=Array.from({length:14},(_,index)=>new Date(today.getTime()+index*86400000));
  return <LmsShell profile={profile} activeRole="student" activePath="/dashboard/student/classes" eyebrow="Learning calendar" title="Classes and confirmations" subtitle={`Your schedule is shown in ${timezone}. Confirm and rate each completed class before it is added to your usage.`}><Notice params={await searchParams}/>
    <div className="metrics-grid class-balance-grid"><Metric label="Plan" value={entitlement?.plan_type??'Not set'} note={entitlement?`Valid until ${new Date(entitlement.expires_at).toLocaleDateString('en-IN',{timeZone:timezone})}`:'Contact the academy to activate'}/><Metric label="Purchased" value={entitlement?.class_allowance??0} note="Total class entitlement" tone="blue"/><Metric label="Classes taken" value={taken} note="Student-confirmed sessions" tone="mint"/><Metric label="Classes remaining" value={remaining} note="Available in your plan" tone="coral"/></div>
    {pending.length>0&&<section className="panel confirmation-panel"><div className="panel-head"><div><span className="panel-kicker">ACTION REQUIRED</span><h2>Confirm your completed classes</h2></div><Status tone="amber">{pending.length} waiting</Status></div>{pending.map(row=><article className="confirmation-card" key={row.id}><div><small>{row.course} · {formatDate(row.starts_at,timezone)}</small><h3>{row.title}</h3><p>Taught by {row.tutor}. Confirm attendance and share a rating to record this class.</p></div><form action="/api/lms" method="post"><input type="hidden" name="action" value="confirm-class"/><input type="hidden" name="classId" value={row.id}/><label>Teacher rating<select name="rating" required defaultValue=""><option value="" disabled>Choose 1–5 stars</option>{[5,4,3,2,1].map(rating=><option value={rating} key={rating}>{'★'.repeat(rating)} ({rating}/5)</option>)}</select></label><label>Feedback (optional)<textarea name="feedback" rows={2} maxLength={1200} placeholder="What helped you in this class?"/></label><button>Confirm class & submit rating</button></form></article>)}</section>}
    <section className="calendar-panel"><header><div><span className="panel-kicker">NEXT 14 DAYS</span><h2>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,month:'long',year:'numeric'}).format(today)}</h2></div><Status>{upcoming.length} upcoming</Status></header><div className="calendar-strip">{days.map(day=>{const key=dateKeyInTimeZone(day,timezone),count=upcoming.filter(r=>dateKeyInTimeZone(r.starts_at,timezone)===key).length;return <div className={key===dateKeyInTimeZone(new Date(),timezone)?'today':''} key={key}><span>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,weekday:'short'}).format(day)}</span><strong>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,day:'numeric'}).format(day)}</strong>{count>0&&<i>{count}</i>}</div>})}</div></section>
    <section className="panel class-agenda"><div className="panel-head"><div><span className="panel-kicker">AGENDA</span><h2>Your scheduled lessons</h2></div></div>{upcoming.length?upcoming.map(r=><article className="agenda-row" key={r.id}><div className="agenda-date"><span>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,weekday:'short'}).format(new Date(r.starts_at))}</span><strong>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,day:'numeric'}).format(new Date(r.starts_at))}</strong><small>{new Intl.DateTimeFormat('en-IN',{timeZone:timezone,month:'short'}).format(new Date(r.starts_at))}</small></div><div className="agenda-detail"><span>{r.course}</span><h3>{r.title}</h3><p>{formatDate(r.starts_at,timezone)} · {r.duration_minutes} minutes · {r.tutor}</p><small>{r.notes||'No preparation notes'}</small></div>{r.meeting_url?<a className="module-link" href={r.meeting_url}>Join class ↗</a>:<Status tone="amber">Link pending</Status>}</article>):<div className="empty-module"><h3>No upcoming classes</h3><p>Your tutor will add your next live lesson here.</p></div>}</section>
  </LmsShell>;
}
