import {all} from "@/db/lms";
import {CopyPlus,LockKeyhole} from "lucide-react";
import CourseStartForm from "../../CourseStartForm";
import {LmsShell,Notice,Status} from "../../components";
import {requireRole} from "../../auth";
import DeleteButton from "../../DeleteButton";
import CourseCatalogFilter from "../../CourseCatalogFilter";

type Course={id:string;title:string;subject:string;level:string;description:string;cover_image_url:string;is_unlocked:number;students:number;chapters:number;lessons:number;creator_role:string;creator_id:string|null;source_course_id:string|null;curriculum:string|null;completion_points:number};
type Student={id:string;name:string};type Enrollment={course_id:string;student_id:string;student:string;progress:number};
type Curriculum={id:string;name:string;audience:string;category:string};type Subject={id:string;curriculum_id:string;name:string;grades_json:string};
type CatalogCourse={id:string;title:string;subject:string;level:string;description:string;chapters:number;lessons:number;curriculum:string|null};
type StaffCourse={id:string;title:string;subject:string;level:string;description:string;progress:number;status:string;completion_points:number;certificate_code:string|null};
export const dynamic="force-dynamic";

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole("tutor","/dashboard/tutor/courses"),tutorId=profile.role==="admin"?"usr_demo_tutor":profile.id,params=await searchParams;
  // The production Supabase endpoint is a transaction pooler. Run this
  // read set in order so query deadlines begin when work starts, rather than
  // while several statements are queued behind one serverless connection.
  const courses=await all<Course>(`SELECT c.id,c.title,c.subject,c.level,c.description,c.cover_image_url,c.is_unlocked,c.creator_role,c.creator_id,c.source_course_id,c.completion_points,cu.name curriculum,(SELECT COUNT(*) FROM enrollments e WHERE e.course_id=c.id) students,(SELECT COUNT(*) FROM chapters ch WHERE ch.course_id=c.id) chapters,(SELECT COUNT(*) FROM lessons l WHERE l.course_id=c.id) lessons FROM courses c LEFT JOIN curricula cu ON cu.id=c.curriculum_id WHERE c.tutor_id=? AND c.status='active' ORDER BY c.created_at DESC`,tutorId);
  const students=await all<Student>("SELECT id,name FROM users WHERE role='student' AND status='active' ORDER BY name");
  const enrollments=await all<Enrollment>(`SELECT e.course_id,e.student_id,u.name student,e.progress FROM enrollments e JOIN courses c ON c.id=e.course_id JOIN users u ON u.id=e.student_id WHERE c.tutor_id=? ORDER BY u.name`,tutorId);
  const curricula=await all<Curriculum>("SELECT id,name,audience,category FROM curricula WHERE status='active' ORDER BY name");
  const subjects=await all<Subject>("SELECT id,curriculum_id,name,grades_json FROM curriculum_subjects WHERE status='active' ORDER BY name");
  const catalog=await all<CatalogCourse>(`SELECT c.id,c.title,c.subject,c.level,c.description,cu.name curriculum,(SELECT COUNT(*) FROM chapters ch WHERE ch.course_id=c.id) chapters,(SELECT COUNT(*) FROM lessons l WHERE l.course_id=c.id) lessons FROM courses c LEFT JOIN curricula cu ON cu.id=c.curriculum_id WHERE c.creator_role='admin' AND c.is_catalog=1 AND c.status='active' AND NOT EXISTS(SELECT 1 FROM courses copy WHERE copy.source_course_id=c.id AND copy.tutor_id=?) ORDER BY c.created_at DESC`,tutorId);
  const development=await all<StaffCourse>(`SELECT se.id,c.title,c.subject,c.level,c.description,se.progress,se.status,c.completion_points,sc.certificate_code FROM staff_course_enrollments se JOIN courses c ON c.id=se.course_id LEFT JOIN staff_certificates sc ON sc.course_id=se.course_id AND sc.tutor_id=se.tutor_id WHERE se.tutor_id=? ORDER BY se.assigned_at DESC`,tutorId);
  const query=(params.q??"").trim(),subject=(params.subject??"").trim(),access=(params.access??"").trim(),needle=query.toLowerCase();
  const visibleCourses=courses.filter(course=>(!needle||`${course.title} ${course.subject} ${course.level} ${course.description} ${course.curriculum??""}`.toLowerCase().includes(needle))&&(!subject||course.subject===subject)&&(!access||(access==="open"?Boolean(course.is_unlocked):!course.is_unlocked)));
  const courseSubjects=[...new Set(courses.map(course=>course.subject))].sort((a,b)=>a.localeCompare(b));
  return <LmsShell profile={profile} activeRole="tutor" activePath="/dashboard/tutor/courses" eyebrow="Teaching programmes" title="My courses" subtitle="Build your own governed courses, import approved admin courses, and assign learners." actions={<a className="module-link" href="/dashboard/tutor/curriculum">Open course builder →</a>}>
    <Notice params={params}/>
    {development.length?<section className="panel professional-development-panel"><div className="panel-head"><div><span className="panel-kicker">PROFESSIONAL DEVELOPMENT</span><h2>Courses assigned by Skillvelop</h2><p>Your academy training record and tutor certificates stay separate from student-facing courses.</p></div><Status>{development.length} assigned</Status></div><div>{development.map(course=><article key={course.id}><div><small>{course.subject} · {course.level}</small><h3>{course.title}</h3><p>{course.description}</p></div><div><strong>{course.status==="completed"?"100%":course.progress+"%"}</strong><span>{course.completion_points} points</span>{course.certificate_code?<small>Certificate {course.certificate_code}</small>:<Status tone="amber">In progress</Status>}</div></article>)}</div></section>:null}
    {catalog.length?<details className="panel course-import-catalog"><summary><CopyPlus size={18}/><span><strong>Import an approved admin course</strong><small>{catalog.length} course{catalog.length===1?"":"s"} available</small></span></summary><div>{catalog.map(course=><article key={course.id}><small>{course.curriculum??"Academy course"} · {course.level}</small><h3>{course.title}</h3><p>{course.description}</p><span>{course.chapters} chapters · {course.lessons} lessons</span><form action="/api/lms" method="post"><input type="hidden" name="action" value="import-course"/><input type="hidden" name="courseId" value={course.id}/><button>Import editable copy</button></form></article>)}</div></details>:null}
    <CourseCatalogFilter action="/dashboard/tutor/courses" query={query} subject={subject} subjects={courseSubjects} filterName="access" filterLabel="Student access" filterValue={access} filterOptions={[{value:"open",label:"Access enabled"},{value:"locked",label:"Locked"}]}/>
    <div className="course-management-layout"><section className="tutor-course-grid">{visibleCourses.map(course=>{const assigned=enrollments.filter(item=>item.course_id===course.id),available=students.filter(student=>!assigned.some(item=>item.student_id===student.id)),protectedCourse=course.creator_role==="admin";return <article className="tutor-course-card" key={course.id}><div className="tutor-course-cover" style={course.cover_image_url?{backgroundImage:`linear-gradient(0deg,rgba(12,31,38,.72),rgba(12,31,38,.05)),url(${course.cover_image_url})`}:undefined}><Status tone={course.is_unlocked?"green":"amber"}>{course.is_unlocked?"Student access on":"Locked"}</Status><span>{course.subject}</span></div><div className="tutor-course-body"><small>{course.curriculum?`${course.curriculum} · `:""}{course.level}{protectedCourse?" · Admin managed":course.source_course_id?" · Imported copy":""}</small><h2>{course.title}</h2><p>{course.description}</p><div className="course-counts"><span><b>{course.chapters}</b> Chapters</span><span><b>{course.lessons}</b> Lessons</span><span><b>{course.completion_points}</b> Points</span></div>
      <form className="unlock-form" action="/api/lms" method="post"><input type="hidden" name="action" value="set-content-unlock"/><input type="hidden" name="entity" value="course"/><input type="hidden" name="id" value={course.id}/><input type="hidden" name="next" value={course.is_unlocked?"0":"1"}/><input type="hidden" name="returnTo" value="/dashboard/tutor/courses?updated=unlock"/><button disabled={protectedCourse}>{course.is_unlocked?"Lock course":"Unlock course for students"}</button></form>
      <form className="course-enrol-form" action="/api/lms" method="post"><input type="hidden" name="action" value="enrol-course-student"/><input type="hidden" name="courseId" value={course.id}/><select name="studentId" required disabled={!available.length}><option value="">{available.length?"Choose student…":"All students assigned"}</option>{available.map(student=><option key={student.id} value={student.id}>{student.name}</option>)}</select><button disabled={!available.length}>Assign course</button></form>
      {assigned.length?<section className="course-student-assignments"><h3>Assigned students</h3>{assigned.map(item=><article key={item.student_id}><span><strong>{item.student}</strong><small>{item.progress}% course progress</small></span><form action="/api/lms" method="post"><input type="hidden" name="action" value="revoke-course-student"/><input type="hidden" name="courseId" value={course.id}/><input type="hidden" name="studentId" value={item.student_id}/><button>Revoke</button></form></article>)}</section>:null}
      {protectedCourse?<p className="protected-content"><LockKeyhole size={14}/> Admin-created course: teaching access only; editing and deletion are protected.</p>:<DeleteButton action="delete-course" id={course.id} name="courseId" label={`course “${course.title}”`}/>}</div></article>})}{!visibleCourses.length?<div className="course-filter-empty"><h3>No matching courses</h3><p>Try a different keyword or clear the filters.</p></div>:null}</section>
      <aside className="form-card sticky-builder"><CourseStartForm mode="tutor" curricula={curricula} subjects={subjects}/></aside>
    </div>
  </LmsShell>;
}

