/* eslint-disable jsx-a11y/media-has-caption, @next/next/no-img-element */
import { all, first } from "@/db/lms";
import { learningItemHref, loadLearningSequence, type LearningItem, type LearningItemType } from "@/db/learning-sequence";
import { renderLessonHtml } from "@/db/lesson-content";
import { requireRole } from "@/app/dashboard/auth";
import { initials } from "@/app/dashboard/components";
import { MathFormField } from "@/app/dashboard/MathComposer";
import MathText from "@/app/dashboard/MathText";
import MatchingQuestion from "@/app/dashboard/student/quizzes/MatchingQuestion";
import OrderQuestion from "@/app/dashboard/student/quizzes/OrderQuestion";
import QuizQuestionResource from "@/app/dashboard/student/quizzes/QuizQuestionResource";
import CourseAIFloat from "@/app/dashboard/CourseAIFloat";
import AssignmentAttachmentField from "@/app/dashboard/student/work/AssignmentAttachmentField";
import { hasStoredCredential } from "@/app/api/ai/provider";
import { notFound } from "next/navigation";
import Image from "next/image";
import { BookOpen, CheckCircle2, ClipboardList, Download, FileQuestion, LockKeyhole, MessageCircle, Paperclip, StickyNote, XCircle } from "lucide-react";

type Course={id:string;title:string;subject:string;level:string;description:string;tutor:string};
type Lesson={id:string;chapter_id:string|null;title:string;summary:string;content:string;content_format:string;embed_url:string;video_url:string;position:number;duration_minutes:number;completed_at:string|null};
type Resource={id:string;title:string;resource_type:string;file_name:string;content_type:string;size_bytes:number};
type Quiz={id:string;title:string;description:string;kind:string;attempt_limit:number;attempts:number;best:number|null;passing_percentage:number};
type Question={id:string;type:string;prompt:string;options_json:string;answer_json:string;points:number;position:number;resource_type:string;resource_embed_url:string;image_file_name:string;image_content_type:string;image_size_bytes:number};
type QuizAttempt={answers_json:string;score:number;max_score:number;submitted_at:string};
type Activity={id:string;title:string;type:string;instructions:string;due_at:string;points:number;submission_id:string|null;response:string|null;submitted_at:string|null;score:number|null;feedback:string|null;status:string|null};
type Attachment={id:string;file_name:string;content_type:string;size_bytes:number};
export const dynamic="force-dynamic";

function videoEmbed(url:string){
  const youtube=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([^?&/]+)/i);if(youtube)return {kind:"embed",src:`https://www.youtube-nocookie.com/embed/${youtube[1]}`};
  const vimeo=url.match(/vimeo\.com\/(?:video\/)?(\d+)/i);if(vimeo)return {kind:"embed",src:`https://player.vimeo.com/video/${vimeo[1]}`};
  return {kind:/\.(mp4|webm|mov)(?:\?|$)/i.test(url)?"file":"embed",src:url};
}
function iconFor(type:LearningItemType){return type==="lesson"?<BookOpen size={16}/>:type==="quiz"?<FileQuestion size={16}/>:<ClipboardList size={16}/>;}
function fileSize(bytes:number){return bytes<1024*1024?`${Math.max(1,Math.round(bytes/1024))} KB`:`${(bytes/1024/1024).toFixed(1)} MB`;}
function parseAnswer(value:string){try{return String(JSON.parse(value));}catch{return value;}}
function normalized(value:string){return value.toLowerCase().replace(/\s*\|\s*/g,"|").replace(/\s*=\s*/g,"=");}

function ResourceViewer({resource}:{resource:Resource}){
  const src=`/api/resources/${resource.id}`;
  if(resource.resource_type==="video")return <article className="embedded-resource"><video src={src} controls preload="metadata"/><footer><strong>{resource.title}</strong><a href={`${src}?download=1`}><Download size={15}/> Download</a></footer></article>;
  if(resource.resource_type==="audio")return <article className="embedded-resource audio"><div><strong>{resource.title}</strong><small>{resource.file_name} · {fileSize(resource.size_bytes)}</small></div><audio src={src} controls preload="metadata"/><a href={`${src}?download=1`} aria-label={`Download ${resource.title}`}><Download size={16}/></a></article>;
  if(resource.resource_type==="image")return <article className="embedded-resource"><img src={src} alt={resource.title}/><footer><strong>{resource.title}</strong><a href={`${src}?download=1`}><Download size={15}/> Download</a></footer></article>;
  if(resource.resource_type==="pdf")return <article className="embedded-resource document"><iframe src={src} title={resource.title}/><footer><div><strong>{resource.title}</strong><small>{resource.file_name} · {fileSize(resource.size_bytes)}</small></div><a href={`${src}?download=1`}><Download size={15}/> Download</a></footer></article>;
  return <article className="resource-download-card"><span>{resource.resource_type==="scorm"?"SCORM":resource.resource_type==="presentation"?"SLIDES":"DOC"}</span><div><strong>{resource.title}</strong><small>{resource.file_name} · {fileSize(resource.size_bytes)}</small></div><a href={src}>Open or download ↗</a></article>;
}

export default async function LearningWindow({params}:{params:Promise<{courseId:string;itemType:string;itemId:string}>}){
  const profile=await requireRole("student","/dashboard/student/curriculum"),studentId=profile.role==="admin"?"usr_demo_student":profile.id;
  const {courseId,itemType,itemId}=await params;if(!["lesson","quiz","activity"].includes(itemType))notFound();
  const [course,sequence]=await Promise.all([
    first<Course>(`SELECT c.id,c.title,c.subject,c.level,c.description,u.name tutor FROM courses c JOIN enrollments e ON e.course_id=c.id AND e.student_id=? JOIN users u ON u.id=c.tutor_id WHERE c.id=? AND c.status='active' AND c.is_unlocked=1`,studentId,courseId),
    loadLearningSequence(courseId,studentId),
  ]);
  if(!course)notFound();const current=sequence.find(item=>item.type===itemType&&item.id===itemId);if(!current?.available)notFound();
  const index=sequence.indexOf(current),previous=sequence[index-1]??null,next=sequence[index+1]??null,currentHref=learningItemHref(current),nextHref=next&&next.tutorUnlocked?learningItemHref(next):currentHref;
  const completed=sequence.filter(item=>item.completed).length,progress=sequence.length?Math.round(completed/sequence.length*100):0;
  const groupMap=new Map<string,{title:string;position:number;items:LearningItem[]}>();for(const item of sequence){const key=item.chapterId??"course";const group=groupMap.get(key)??{title:item.chapterTitle,position:item.chapterPosition,items:[]};group.items.push(item);groupMap.set(key,group);}const groups=[...groupMap.values()].sort((a,b)=>a.position-b.position);

  const lessonPromise=current.type==="lesson"?first<Lesson>(`SELECT l.id,l.chapter_id,l.title,l.summary,l.content,l.content_format,l.embed_url,l.video_url,l.position,l.duration_minutes,lp.completed_at FROM lessons l LEFT JOIN lesson_progress lp ON lp.lesson_id=l.id AND lp.student_id=? WHERE l.id=?`,studentId,current.id):Promise.resolve(null);
  const resourcesPromise=current.type==="lesson"?all<Resource>("SELECT id,title,resource_type,file_name,content_type,size_bytes FROM lesson_resources WHERE lesson_id=? ORDER BY created_at",current.id):Promise.resolve([]);
  const notePromise=current.type==="lesson"?first<{body:string;updated_at:string}>("SELECT body,updated_at FROM lesson_notes WHERE lesson_id=? AND student_id=?",current.id,studentId):Promise.resolve(null);
  const quizPromise=current.type==="quiz"?first<Quiz>(`SELECT q.id,q.title,q.description,q.kind,q.attempt_limit,q.passing_percentage,COUNT(qa.id) attempts,MAX(CASE WHEN qa.max_score>0 THEN ROUND(qa.score*100.0/qa.max_score) END) best FROM quizzes q LEFT JOIN quiz_attempts qa ON qa.quiz_id=q.id AND qa.student_id=? WHERE q.id=? AND q.scope='course' GROUP BY q.id`,studentId,current.id):Promise.resolve(null);
  const questionsPromise=current.type==="quiz"?all<Question>("SELECT id,type,prompt,options_json,answer_json,points,position,resource_type,resource_embed_url,image_file_name,image_content_type,image_size_bytes FROM quiz_questions WHERE quiz_id=? ORDER BY position",current.id):Promise.resolve([]);
  const quizAttemptPromise=current.type==="quiz"?first<QuizAttempt>("SELECT answers_json,score,max_score,submitted_at FROM quiz_attempts WHERE quiz_id=? AND student_id=? ORDER BY submitted_at DESC LIMIT 1",current.id,studentId):Promise.resolve(null);
  const resetRequestPromise=current.type==="quiz"?first<{status:string}>("SELECT status FROM assessment_reset_requests WHERE quiz_id=? AND learner_id=? ORDER BY requested_at DESC LIMIT 1",current.id,studentId):Promise.resolve(null);
  const activityPromise=current.type==="activity"?first<Activity>(`SELECT a.id,a.title,a.type,a.instructions,a.due_at,a.points,s.id submission_id,s.response,s.submitted_at,s.score,s.feedback,s.status FROM activities a LEFT JOIN submissions s ON s.activity_id=a.id AND s.student_id=? WHERE a.id=?`,studentId,current.id):Promise.resolve(null);
  const [lesson,resources,note,quiz,questions,quizAttempt,resetRequest,activity,plan,ai]=await Promise.all([lessonPromise,resourcesPromise,notePromise,quizPromise,questionsPromise,quizAttemptPromise,resetRequestPromise,activityPromise,first<{plan_type:string;expires_at:string}>("SELECT plan_type,expires_at FROM student_subscriptions WHERE student_id=?",studentId),first<{provider:"openai"|"anthropic";enabled:number}>("SELECT provider,enabled FROM ai_settings WHERE id='platform'")]);
  const attachments=activity?.submission_id?await all<Attachment>("SELECT id,file_name,content_type,size_bytes FROM submission_attachments WHERE submission_id=? ORDER BY created_at",activity.submission_id):[];
  const assistantEnabled=Boolean(plan?.plan_type==="paid"&&plan.expires_at>new Date().toISOString()&&ai?.enabled&&await hasStoredCredential(ai.provider));
  const returnAfterCompletion=next&&next.tutorUnlocked?nextHref:currentHref;

  return <div className="course-player sequence-player">
    <aside className="player-sidebar"><div className="learner-mode">Your guided learning path</div><a className="player-back" href={`/dashboard/student/curriculum/${course.id}`}>← Course overview</a><div className="player-course-card"><span>{course.subject} · {course.level}</span><h2>{course.title}</h2><div className="player-progress"><i style={{width:`${progress}%`}}/></div><small>{completed} of {sequence.length} activities complete · {progress}%</small></div><nav aria-label="Course learning sequence">{groups.map(group=><section className="player-chapter-group" key={`${group.position}-${group.title}`}><header><span>CHAPTER {group.position}</span><strong>{group.title}</strong></header>{group.items.map(item=>item.available?<a className={item.id===current.id&&item.type===current.type?"active":item.completed?"complete":""} href={learningItemHref(item)} key={`${item.type}-${item.id}`}><span>{item.completed?<CheckCircle2 size={15}/>:iconFor(item.type)}</span><div><small>{item.label}</small><strong>{item.title}</strong></div><i>{item.id===current.id&&item.type===current.type?"●":"›"}</i></a>:<div className="locked" key={`${item.type}-${item.id}`}><span><LockKeyhole size={14}/></span><div><small>{item.label}</small><strong>{item.title}</strong></div><i><LockKeyhole size={13}/></i></div>)}</section>)}</nav><div className="player-tutor"><span>{initials(course.tutor)}</span><div><small>YOUR TUTOR</small><strong>{course.tutor}</strong></div><a href="/dashboard/student/messages">Message</a></div></aside>
    <main className="player-main"><header className="player-topbar"><div><a className="player-brand" href="/dashboard/student" aria-label="Skillvelop dashboard"><Image src="/skillvelop-logo.png" alt="Skillvelop" width={120} height={80} priority unoptimized /></a><i>/</i><b>{current.chapterTitle}</b></div><div><a href="/dashboard/student/messages" aria-label="Message your tutor"><MessageCircle size={18}/></a><span>{initials(profile.name)}</span></div></header>
      <section className="player-canvas"><div className="lesson-breadcrumb"><span>Chapter {current.chapterPosition}</span> / {current.label} / Step {index+1} of {sequence.length}</div>
        {lesson?<article className="lesson-stage learning-item-stage"><span className="lesson-subject-chip">{course.subject} · {lesson.content_format.replaceAll("_"," ")}</span><h1>{lesson.title}</h1><p className="lesson-intro">{lesson.summary}</p><div className="lesson-facts"><span>◷ {lesson.duration_minutes} minutes</span><span>⚡ 50 XP on completion</span><span>{lesson.completed_at?"✓ Completed":"○ In progress"}</span></div>
          {(lesson.embed_url||lesson.video_url)&&lesson.content_format==="video"?(()=>{const video=videoEmbed(lesson.embed_url||lesson.video_url);return video.kind==="file"?<video className="lesson-video" src={video.src} controls preload="metadata"/>:<div className="lesson-video-frame"><iframe src={video.src} title={`${lesson.title} video`} allow="accelerometer; autoplay; encrypted-media; picture-in-picture" allowFullScreen/></div>})():null}
          {lesson.embed_url&&lesson.content_format==="audio"?<audio className="lesson-audio" src={lesson.embed_url} controls preload="metadata"/>:null}
          {lesson.embed_url&&(lesson.content_format==="iframe"||lesson.content_format==="game")?<div className="lesson-iframe"><iframe src={lesson.embed_url} title={lesson.content_format==="game"?`${lesson.title} learning game`:lesson.title} allowFullScreen loading="lazy" referrerPolicy="no-referrer" sandbox="allow-forms allow-popups allow-presentation allow-same-origin allow-scripts"/></div>:null}
          <div className="rich-lesson-content" dangerouslySetInnerHTML={{__html:renderLessonHtml(lesson.content)}}/>
          {resources.length?<section className="player-resource-grid"><header><span className="panel-kicker">EMBEDDED LEARNING MATERIALS</span><h2>Learn without leaving this window</h2></header>{resources.map(resource=><ResourceViewer resource={resource} key={resource.id}/>)}</section>:null}
          <section className="private-lesson-notes"><header><span><StickyNote size={19}/></span><div><small>PRIVATE LESSON NOTES</small><h2>Your notes for this lesson</h2><p>Only you and your tutor can view these notes.</p></div></header><form action="/api/lms" method="post"><input type="hidden" name="action" value="save-lesson-note"/><input type="hidden" name="lessonId" value={lesson.id}/><input type="hidden" name="returnTo" value={currentHref}/><textarea name="body" rows={6} defaultValue={note?.body??""} placeholder="Capture explanations, examples, questions and formulas you want to revisit…"/><button>Save private notes</button></form>{note?<small>Last saved {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(note.updated_at))}</small>:null}</section>
        </article>:null}

        {quiz?<article className="lesson-stage learning-item-stage inline-quiz"><span className="lesson-subject-chip">{quiz.kind.replaceAll("_"," ")}</span><h1>{quiz.title}</h1><p className="lesson-intro">{quiz.description}</p><div className="lesson-facts"><span>{quiz.kind==="quiz"?`${quiz.attempt_limit} attempts allowed`:"One recorded attempt"}</span><span>{quiz.best!==null?`${quiz.best>=quiz.passing_percentage?"Passed":"Not passed"} · ${quiz.best}%`:"Not attempted"}</span><span>Pass mark {quiz.passing_percentage}%</span></div>
          {quizAttempt?(()=>{let submitted:Record<string,string>={};try{submitted=JSON.parse(quizAttempt.answers_json) as Record<string,string>;}catch{submitted={};}return <section className="quiz-answer-review compact"><div className="quiz-result-summary"><strong>{quizAttempt.max_score?Math.round(quizAttempt.score*100/quizAttempt.max_score):0}% · {quizAttempt.max_score&&quizAttempt.score*100/quizAttempt.max_score>=quiz.passing_percentage?"Pass":"Fail"}</strong><span>Your latest answers</span></div>{questions.map((question,index)=>{const given=submitted[question.id]??"",correct=parseAnswer(question.answer_json),isCorrect=normalized(given)===normalized(correct);return <article className={isCorrect?"answer-review-card correct":"answer-review-card incorrect"} key={question.id}><header><span>{isCorrect?<CheckCircle2 size={18}/>:<XCircle size={18}/>}</span><div><small>QUESTION {index+1}</small><MathText text={question.prompt}/></div><strong>{isCorrect?"Correct":"Incorrect"}</strong></header><QuizQuestionResource question={question} index={index}/>{!isCorrect?<div className="correct-answer"><span>Correct answer</span><MathText text={correct}/></div>:null}</article>})}</section>})():null}
          {quiz.attempts>=quiz.attempt_limit?<><div className="inline-completion"><CheckCircle2 size={24}/><div><strong>{quiz.best!==null&&quiz.best>=quiz.passing_percentage?"Quiz passed":"Attempt recorded"}</strong><p>{quiz.best!==null&&quiz.best>=quiz.passing_percentage?`You reached the ${quiz.passing_percentage}% pass mark.`:`Your result is saved. The pass mark is ${quiz.passing_percentage}%.`}</p></div></div>{quiz.kind==="final_assessment"?<section className="assessment-reset-request">{resetRequest?.status==="pending"?<p>Your re-attempt request is awaiting tutor approval.</p>:<form action="/api/lms" method="post"><input type="hidden" name="action" value="request-assessment-reset"/><input type="hidden" name="quizId" value={quiz.id}/><input type="hidden" name="returnTo" value={currentHref}/><label>Request another attempt<textarea name="reason" rows={3} required placeholder="Tell your tutor why you are ready to re-attempt this final assessment."/></label><button>Send re-attempt request</button></form>}</section>:null}</>:questions.length?<form action="/api/lms" method="post" className="inline-quiz-form"><input type="hidden" name="action" value="submit-quiz"/><input type="hidden" name="quizId" value={quiz.id}/><input type="hidden" name="returnTo" value={returnAfterCompletion}/>{questions.map((question,questionIndex)=>{const options=JSON.parse(question.options_json||"[]") as string[];return <section className={`question-card ${question.type}`} key={question.id}><div className="question-heading"><span className="question-index">{questionIndex+1}</span><div><small>{question.points} POINTS · {question.type.replaceAll("_"," ")}</small><MathText className="question-prompt" text={question.prompt}/></div></div><QuizQuestionResource question={question} index={questionIndex}/>{question.type==="mcq"?<div className="choice-grid">{options.map((option,optionIndex)=><label className="choice" key={`${option}-${optionIndex}`}><input type="radio" name={`answer_${question.id}`} value={option} required/><span><b>{String.fromCharCode(65+optionIndex)}</b><MathText text={option}/></span></label>)}</div>:question.type==="matching"?<MatchingQuestion name={`answer_${question.id}`} items={options}/>:question.type==="order"||question.type==="drag_drop"?<OrderQuestion name={`answer_${question.id}`} items={options}/>:<MathFormField name={`answer_${question.id}`} compact required placeholder={question.type==="fill_blank"?"Complete the blank with text or maths":"Type your answer or equation"}/>}</section>})}<button className="quiz-submit">Submit & continue →</button></form>:<div className="inline-completion waiting"><FileQuestion size={24}/><div><strong>Questions are being prepared</strong><p>Your tutor will make this activity available soon.</p></div></div>}
        </article>:null}

        {activity?<article className="lesson-stage learning-item-stage inline-assignment"><span className="lesson-subject-chip">{activity.type.replaceAll("_"," ")}</span><h1>{activity.title}</h1><p className="lesson-intro">{activity.instructions}</p><div className="lesson-facts"><span>Due {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(activity.due_at))}</span><span>{activity.points} points</span><span>{activity.submission_id?"✓ Submitted":"○ To complete"}</span></div>
          {activity.submission_id?<section className="submitted-assignment"><header><CheckCircle2 size={22}/><div><strong>Submitted for tutor review</strong><small>{activity.submitted_at?new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(activity.submitted_at)):"Saved"}</small></div>{activity.score!==null?<b>{activity.score} points</b>:null}</header>{activity.response?<p>{activity.response}</p>:null}{attachments.length?<div className="student-attachment-list">{attachments.map(file=><a href={`/api/submission-attachments/${file.id}`} key={file.id}><Paperclip size={16}/><span><strong>{file.file_name}</strong><small>{fileSize(file.size_bytes)}</small></span><Download size={16}/></a>)}</div>:null}{activity.feedback?<div className="feedback-box"><strong>Tutor feedback</strong><p>{activity.feedback}</p></div>:null}</section>:<form action="/api/lms" method="post" encType="multipart/form-data" className="inline-assignment-form"><input type="hidden" name="action" value="submit-activity"/><input type="hidden" name="activityId" value={activity.id}/><input type="hidden" name="returnTo" value={returnAfterCompletion}/><MathFormField name="response" label="Your response (optional when attaching files)" multiline placeholder="Write your answer, show your working, or explain the files you are submitting…"/><AssignmentAttachmentField/><button>Submit assignment & continue →</button></form>}
        </article>:null}
      </section>
      <footer className="player-footer sequence-footer">{previous?<a href={learningItemHref(previous)}>← Previous: {previous.title}</a>:<a href={`/dashboard/student/curriculum/${course.id}`}>← Course overview</a>}{current.completed?(next&&next.tutorUnlocked?<a className="complete-button" href={nextHref}>Continue: {next.title} →</a>:<a className="complete-button" href={progress===100?"/dashboard/student/certificates":`/dashboard/student/curriculum/${course.id}`}>{progress===100?"View certificate":"Return to course"} →</a>):lesson?<form action="/api/lms" method="post"><input type="hidden" name="action" value="complete-lesson"/><input type="hidden" name="lessonId" value={lesson.id}/><input type="hidden" name="returnTo" value={returnAfterCompletion}/><button className="complete-button">Complete & continue →</button></form>:<span className="sequence-tip">Complete this activity to unlock the next step.</span>}</footer>
      {assistantEnabled?<CourseAIFloat courseId={course.id} chapterId={current.chapterId} lessonId={lesson?.id} contextLabel={`${current.chapterTitle} · ${current.title}`}/>:null}
    </main>
  </div>;
}
