import { getChatGPTUser, safeRelativeReturnPath } from "@/app/chatgpt-auth";
import Image from "next/image";

export const dynamic = "force-dynamic";

export default async function LoginPage({ searchParams }: { searchParams: Promise<{ error?: string; returnTo?: string }> }) {
  const params = await searchParams;
  const user = await getChatGPTUser();
  const returnTo = safeRelativeReturnPath(params.returnTo || "/dashboard");
  return <main className="login-page"><a className="brand login-brand brand-logo-shell" href="/" aria-label="Skillvelop Academy home"><Image src="/skillvelop-logo.png" alt="Skillvelop" width={140} height={93} priority unoptimized /></a><section className="login-card"><div className="login-copy"><span className="kicker">YOUR LEARNING SPACE</span><h1>Welcome back to<br/><em>better learning.</em></h1><p>One secure account for live 1:1 classes, assigned work, tutor feedback and measurable progress.</p><div className="login-benefits"><span><i>✓</i> Student LMS and progress</span><span><i>✓</i> Tutor teaching studio</span><span><i>✓</i> Admin operations centre</span></div></div><div className="login-panel"><span className="login-icon"><Image src="/skillvelop-logo.png" alt="" width={156} height={104} unoptimized /></span><h2>{user ? `Continue as ${user.displayName}` : "Sign in to Skillvelop"}</h2><p>Use the username or email assigned by your Skillvelop administrator.</p>{params.error && <div className="auth-error" role="alert">The username or password is incorrect.</div>}{user ? <a className="button button-primary login-button" href={returnTo}>Open my dashboard <span>→</span></a> : <form className="login-form" action="/api/auth/login" method="post"><input type="hidden" name="returnTo" value={returnTo}/><label>Username or email<input name="identifier" required autoComplete="username" placeholder="Your Skillvelop username"/></label><label>Password<input type="password" name="password" required autoComplete="current-password" placeholder="Enter your password"/></label><button className="button button-primary login-button" type="submit">Sign in securely <span>→</span></button></form>}<small>By continuing, you agree to Skillvelop&apos;s learning platform terms and privacy policy.</small></div></section><footer className="login-footer"><span>© 2026 Skillvelop Academy</span><a href="mailto:support@skillvelop.com">Need help?</a></footer></main>;
}
