import { all, first } from "@/db/lms";
import { supportedTimeZones } from "@/db/timezones";
import { LmsShell, Notice } from "../../../components";
import { requireRole } from "../../../auth";
type Row={id:string;name:string};type Course={id:string;title:string};

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole("tutor","/dashboard/tutor/classes/new"),tutorId=profile.role==='admin'?'usr_demo_tutor':profile.id;
  const courses=await all<Course>("SELECT id,title FROM courses WHERE tutor_id=? AND status='active' ORDER BY title",tutorId);
  const students=await all<Row>(`SELECT DISTINCT u.id,u.name FROM users u JOIN enrollments e ON e.student_id=u.id JOIN courses c ON c.id=e.course_id WHERE c.tutor_id=? ORDER BY u.name`,tutorId);
  const timezone=(await first<{timezone:string}>("SELECT timezone FROM user_profiles WHERE user_id=?",tutorId))?.timezone??"Asia/Kolkata";
  return <LmsShell profile={profile} activeRole="tutor" activePath="/dashboard/tutor/classes" eyebrow="Live teaching" title="Schedule a class" subtitle="Enter the class in your own timezone. Skillvelop automatically converts the same moment for every learner." actions={<a className="module-link secondary" href="/dashboard/tutor/classes">← My classes</a>}><Notice params={await searchParams}/><div className="form-page"><section className="form-card"><form action="/api/lms" method="post"><input type="hidden" name="action" value="schedule-class"/><label>Course<select name="courseId" required><option value="">Choose course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Student<select name="studentId" required><option value="">Choose student</option>{students.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Class title<input name="title" required placeholder="Algebra problem solving"/></label><div className="form-row"><label>Starts at<input name="startsAt" type="datetime-local" required/></label><label>Minutes<input name="duration" type="number" min="15" max="180" defaultValue="60"/></label></div><label>Schedule timezone<select name="timeZone" defaultValue={timezone} required>{supportedTimeZones().map(zone=><option value={zone} key={zone}>{zone.replaceAll('_',' ')}</option>)}</select><small>The student will see this automatically in their saved timezone.</small></label><label>Meeting link <span className="required-label">Required</span><input name="meetingUrl" type="url" inputMode="url" required placeholder="https://meet.google.com/..."/><small>Use a secure HTTPS classroom link.</small></label><button>Schedule class →</button></form></section><aside className="help-card"><h3>Timezone-safe scheduling</h3><p>The selected timezone is used only to interpret the date and time you enter. Skillvelop stores one universal class moment, then presents it locally to each tutor and student.</p></aside></div></LmsShell>;
}

