import type { Metadata } from "next";
import { headers } from "next/headers";
import { notFound } from "next/navigation";
import Image from "next/image";
import { Award, BadgeCheck, BookOpen, BriefcaseBusiness, ExternalLink, GraduationCap, Languages, MapPin, MessageCircleHeart, Sparkles, Star, UsersRound } from "lucide-react";
import { all, first } from "@/db/lms";

type Tutor={id:string;public_id:string;name:string;bio:string;headline:string;qualifications:string;experience_years:number;specialties:string;achievements:string;teaching_philosophy:string;location:string;languages:string;linkedin_url:string;website_url:string;avatar_r2_key:string;intro_video_url:string;subject_areas:string;grade_levels:string;certifications:string};
type Course={id:string;title:string;subject:string;level:string;description:string;students:number};
async function tutor(publicId:string){return first<Tutor>(`SELECT u.id,u.public_id,u.name,p.bio,p.headline,p.qualifications,p.experience_years,p.specialties,p.achievements,p.teaching_philosophy,p.location,p.languages,p.linkedin_url,p.website_url,p.avatar_r2_key,p.intro_video_url,p.subject_areas,p.grade_levels,p.certifications FROM users u JOIN user_profiles p ON p.user_id=u.id WHERE u.public_id=? AND u.role='tutor' AND u.status='active' AND p.is_public=1`,publicId);}
function initials(name:string){return name.split(/\s+/).map(part=>part[0]).join("").slice(0,2).toUpperCase();}
function introVideo(url:string){const youtube=url.match(/(?:youtu\.be\/|youtube\.com\/(?:watch\?v=|embed\/))([^?&/]+)/i);if(youtube)return `https://www.youtube-nocookie.com/embed/${youtube[1]}`;const vimeo=url.match(/vimeo\.com\/(?:video\/)?(\d+)/i);if(vimeo)return `https://player.vimeo.com/video/${vimeo[1]}`;return url;}
export async function generateMetadata({params}:{params:Promise<{publicId:string}>}):Promise<Metadata>{const {publicId}=await params;const record=await tutor(publicId);if(!record)return {title:"Tutor not found · Skillvelop",description:"This Skillvelop tutor profile is not available.",openGraph:{images:[]},twitter:{images:[]}};const h=await headers(),host=h.get("x-forwarded-host")||h.get("host"),proto=h.get("x-forwarded-proto")||"https",image=record.avatar_r2_key&&host?`${proto}://${host}/api/profile-photo/${record.public_id}`:undefined,description=record.headline||record.bio||`Meet ${record.name}, a verified Skillvelop tutor.`;return {title:`${record.name} · Skillvelop Tutor`,description,openGraph:{title:`${record.name} · Skillvelop Tutor`,description,images:image?[image]:[]},twitter:{title:`${record.name} · Skillvelop Tutor`,description,images:image?[image]:[]}};}

export default async function Page({params}:{params:Promise<{publicId:string}>}){const {publicId}=await params;const record=await tutor(publicId);if(!record)notFound();const courses=await all<Course>(`SELECT c.id,c.title,c.subject,c.level,c.description,COUNT(e.id) students FROM courses c LEFT JOIN enrollments e ON e.course_id=c.id WHERE c.tutor_id=? AND c.status='active' GROUP BY c.id ORDER BY c.created_at DESC LIMIT 6`,record.id);const classes=await first<{total:number}>("SELECT COUNT(*) total FROM live_classes WHERE tutor_id=? AND status='completed'",record.id),rating=await first<{average:number|null;total:number}>("SELECT ROUND(AVG(student_rating),1) average,COUNT(student_rating) total FROM live_classes WHERE tutor_id=? AND status='completed' AND student_rating IS NOT NULL",record.id),students=await first<{total:number}>("SELECT COUNT(DISTINCT e.student_id) total FROM enrollments e JOIN courses c ON c.id=e.course_id WHERE c.tutor_id=?",record.id);const specialties=record.specialties.split(/[,\n]/).map(item=>item.trim()).filter(Boolean),qualifications=record.qualifications.split(/\n/).map(item=>item.trim()).filter(Boolean),achievements=record.achievements.split(/\n/).map(item=>item.trim()).filter(Boolean),certifications=record.certifications.split(/\n/).map(item=>item.trim()).filter(Boolean),subjects=record.subject_areas.split(/[,\n]/).map(item=>item.trim()).filter(Boolean);return <main className="tutor-public-page">
  <nav className="tutor-public-nav"><a href="/" aria-label="Skillvelop home"><Image src="/skillvelop-logo.png" alt="Skillvelop" width={155} height={102} priority unoptimized/></a><div><a href="/#paths">Learning paths</a><a href="/login">LMS login →</a></div></nav>
  <section className="tutor-public-hero"><div className="tutor-avatar-shell">{record.avatar_r2_key?<img src={`/api/profile-photo/${record.public_id}`} alt={record.name}/>:<span>{initials(record.name)}</span>}<i><BadgeCheck size={24}/></i></div><div className="tutor-public-intro"><span className="public-verified"><BadgeCheck size={16}/> VERIFIED SKILLVELOP TUTOR</span><h1>{record.name}</h1><p className="tutor-headline">{record.headline||"Dedicated live 1:1 educator"}</p><div className="tutor-facts"><span><MapPin size={17}/>{record.location||"Online worldwide"}</span><span><BriefcaseBusiness size={17}/>{record.experience_years} years experience</span><span><Languages size={17}/>{record.languages||"English"}</span></div><div className="tutor-public-actions"><a href="/login">Learn with {record.name.split(' ')[0]} →</a>{record.linkedin_url&&<a className="secondary" href={record.linkedin_url} rel="noreferrer" target="_blank">LinkedIn <ExternalLink size={15}/></a>}{record.website_url&&<a className="secondary" href={record.website_url} rel="noreferrer" target="_blank">Website <ExternalLink size={15}/></a>}</div></div><aside className="tutor-id-card"><span>SKILLVELOP EDUCATOR ID</span><strong>{record.public_id}</strong><small>Permanent verified teaching identity</small></aside></section>
  <section className="tutor-public-stats"><article><UsersRound/><strong>{students?.total??0}</strong><span>Learners guided</span></article><article><BookOpen/><strong>{courses.length}</strong><span>Active courses</span></article><article><MessageCircleHeart/><strong>{classes?.total??0}</strong><span>Confirmed live classes</span></article><article><Star/><strong>{rating?.average??'New'}</strong><span>{rating?.total??0} student rating{rating?.total===1?'':'s'}</span></article></section>
  <section className="tutor-public-grid"><div className="tutor-public-main"><article className="public-profile-card"><span className="public-kicker">MEET YOUR TUTOR</span><h2>About {record.name.split(' ')[0]}</h2><p>{record.bio||"A committed educator focused on making live 1:1 learning clear, encouraging and measurable."}</p>{record.intro_video_url?<div className="tutor-intro-video"><iframe src={introVideo(record.intro_video_url)} title={`${record.name} introduction video`} allow="encrypted-media; picture-in-picture" allowFullScreen loading="lazy" referrerPolicy="no-referrer" sandbox="allow-scripts allow-same-origin allow-presentation"/></div>:null}</article><article className="public-profile-card"><span className="public-kicker">TEACHING APPROACH</span><h2>Learning with purpose</h2><p>{record.teaching_philosophy||"Every learner deserves patient guidance, useful feedback and lessons that connect knowledge to confident action."}</p></article><section className="public-course-section"><span className="public-kicker">CURRENT PROGRAMMES</span><h2>Courses taught</h2><div className="public-course-grid">{courses.map(course=><article key={course.id}><i>{course.subject.slice(0,2).toUpperCase()}</i><span>{course.subject} · {course.level}</span><h3>{course.title}</h3><p>{course.description}</p><small>{course.students} learner{course.students===1?'':'s'} currently enrolled</small></article>)}</div></section></div><aside className="tutor-public-sidebar"><article><GraduationCap/><span className="public-kicker">ACADEMICS</span><h3>Qualifications</h3>{qualifications.length?<ul>{qualifications.map(item=><li key={item}>{item}</li>)}</ul>:<p>Academic credentials are being updated.</p>}</article><article><Sparkles/><span className="public-kicker">EXPERTISE</span><h3>Subjects & grades</h3><div className="specialty-cloud">{subjects.length?subjects.map(item=><span key={item}>{item}</span>):specialties.length?specialties.map(item=><span key={item}>{item}</span>):<span>Live 1:1 learning</span>}</div>{record.grade_levels?<p>{record.grade_levels}</p>:null}</article><article><Award/><span className="public-kicker">CERTIFICATIONS</span><h3>Professional credentials</h3>{certifications.length?<ul>{certifications.map(item=><li key={item}>{item}</li>)}</ul>:achievements.length?<ul>{achievements.map(item=><li key={item}>{item}</li>)}</ul>:<p>Professional credentials are being updated.</p>}</article></aside></section>
  <footer className="tutor-public-footer"><Image src="/skillvelop-logo.png" alt="Skillvelop" width={130} height={86} unoptimized/><p>Live 1:1 learning, shaped around every learner.</p><a href="/login">Enter Skillvelop LMS →</a></footer>
  </main>;}
