import { all } from "@/db/lms";
import { LmsShell, Notice, Status } from "../../components";
import { requireRole } from "../../auth";
import QuizQuestionBuilder from "./QuizQuestionBuilder";

type C = { id: string; title: string };
type Ch = { id: string; course_id: string; title: string; position: number };
type Q = { id: string; title: string; description: string; kind: string; course: string; chapter: string | null; questions: number; attempts: number; is_unlocked: number };
export const dynamic = "force-dynamic";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string, string | undefined>> }) {
  const profile = await requireRole("tutor", "/dashboard/tutor/quizzes");
  const tutorId = profile.role === "admin" ? "usr_demo_tutor" : profile.id;
  const courses = await all<C>("SELECT id,title FROM courses WHERE tutor_id=? AND status='active'", tutorId);
  const chapters = await all<Ch>("SELECT id,course_id,title,position FROM chapters WHERE tutor_id=? ORDER BY course_id,position", tutorId);
  const quizzes = await all<Q>(`SELECT q.id,q.title,q.description,q.kind,q.is_unlocked,c.title course,ch.title chapter,COUNT(DISTINCT qq.id) questions,COUNT(DISTINCT qa.id) attempts FROM quizzes q JOIN courses c ON c.id=q.course_id LEFT JOIN chapters ch ON ch.id=q.chapter_id LEFT JOIN quiz_questions qq ON qq.quiz_id=q.id LEFT JOIN quiz_attempts qa ON qa.quiz_id=q.id WHERE q.tutor_id=? GROUP BY q.id ORDER BY c.title,ch.position,q.created_at`, tutorId);
  return <LmsShell profile={profile} activeRole="tutor" activePath="/dashboard/tutor/quizzes" eyebrow="Interactive assessment studio" title="Quiz maker" subtitle="Create engaging, media-rich questions with maths formatting, purpose-built answer fields, and controlled student access.">
    <Notice params={await searchParams} />
    <div className="quiz-maker-intro"><div><span>ASSESSMENT WORKFLOW</span><h2>Build better knowledge checks</h2><p>Create the quiz, open it below, then add question types that behave exactly as learners expect.</p></div><ol><li><b>1</b>Create the quiz</li><li><b>2</b>Add interactive questions</li><li><b>3</b>Preview and unlock</li></ol></div>
    <div className="quiz-builder-grid">
      <section className="panel quiz-structure-panel"><div className="panel-head"><div><span className="panel-kicker">YOUR QUIZZES</span><h2>Course assessment structure</h2></div><Status>{quizzes.length} items</Status></div>{quizzes.length ? quizzes.map(q => <details className="quiz-admin-card" id={`quiz-${q.id}`} key={q.id}><summary><div><small>{q.course} · {q.chapter ?? "Course level"} · {q.kind.replaceAll("_", " ")}</small><h3>{q.title}</h3><p>{q.description}</p><div className="quiz-summary-stats"><span>{q.questions} questions</span><span>{q.attempts} attempts</span></div></div><div className="quiz-admin-actions"><Status tone={q.is_unlocked ? "green" : "amber"}>{q.is_unlocked ? "Unlocked" : "Locked"}</Status><form className="mini-unlock" action="/api/lms" method="post"><input type="hidden" name="action" value="set-content-unlock" /><input type="hidden" name="entity" value="quiz" /><input type="hidden" name="id" value={q.id} /><input type="hidden" name="next" value={q.is_unlocked ? "0" : "1"} /><input type="hidden" name="returnTo" value="/dashboard/tutor/quizzes?updated=unlock" /><button>{q.is_unlocked ? "Lock" : "Unlock"}</button></form></div></summary><QuizQuestionBuilder quizId={q.id} nextPosition={q.questions + 1} /></details>) : <div className="empty-module"><h3>No quizzes yet</h3><p>Use the setup panel to create your first chapter knowledge check.</p></div>}</section>
      <aside className="form-card sticky-builder quiz-setup-card"><form action="/api/lms" method="post"><input type="hidden" name="action" value="create-quiz" /><span className="panel-kicker">STEP 1</span><h2>Create a quiz</h2><p>Choose where it belongs and how many attempts students receive.</p><label>Course<select name="courseId" required><option value="">Choose course</option>{courses.map(course => <option key={course.id} value={course.id}>{course.title}</option>)}</select></label><label>Chapter<select name="chapterId" required><option value="">Choose chapter</option>{chapters.map(chapter => <option key={chapter.id} value={chapter.id}>{courses.find(course => course.id === chapter.course_id)?.title} · Ch {chapter.position}: {chapter.title}</option>)}</select></label><label>Assessment type<select name="kind"><option value="quiz">Practice quiz · repeatable</option><option value="assessment">Assessment · one attempt</option><option value="final_assessment">Final assessment · one attempt</option></select></label><label>Quiz title<input name="title" required placeholder="Fractions mastery check" /></label><label>Student instructions<textarea name="description" rows={4} required placeholder="Explain what this quiz checks and how to prepare." /></label><label>Practice quiz attempt limit<input name="attemptLimit" type="number" min="1" max="10" defaultValue="3" /></label><label className="check-row"><input type="checkbox" name="isUnlocked" /> Unlock for students now</label><button>Create quiz →</button></form></aside>
    </div>
  </LmsShell>;
}
