import { all } from "@/db/lms";
import { LmsShell, Notice, Status } from "../../components";
import DeleteButton from "../../DeleteButton";
import { requireRole } from "../../auth";
import QuizQuestionBuilder from "./QuizQuestionBuilder";
import MathText from "../../MathText";

type Student={id:string;name:string};
type Quiz={id:string;title:string;description:string;question_count:number;questions:number;attempts:number;assignments:number;is_unlocked:number};
type Assignment={id:string;quiz_id:string;student_id:string|null;student:string|null;assigned_at:string};
type Attempt={id:string;quiz_id:string;quiz:string;scope:string;kind:string;student_id:string;student:string;answers_json:string;score:number;max_score:number;submitted_at:string};
type ReviewQuestion={id:string;quiz_id:string;prompt:string;answer_json:string;position:number};
type ResetRequest={id:string;quiz_id:string;quiz:string;learner_id:string;student:string;reason:string;requested_at:string};
export const dynamic="force-dynamic";

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole("tutor","/dashboard/tutor/quizzes"),tutorId=profile.role==="admin"?"usr_demo_tutor":profile.id;
  // Keep reads sequential on the single serverless connection so the timeout
  // measures database work, not time spent waiting behind sibling queries.
  const students=await all<Student>("SELECT id,name FROM users WHERE role='student' AND status='active' ORDER BY name");
  const quizzes=await all<Quiz>(`SELECT q.id,q.title,q.description,q.question_count,q.is_unlocked,
      (SELECT COUNT(*) FROM quiz_questions qq WHERE qq.quiz_id=q.id) questions,
      (SELECT COUNT(*) FROM quiz_attempts qa WHERE qa.quiz_id=q.id) attempts,
      (SELECT COUNT(*) FROM quiz_assignments qas WHERE qas.quiz_id=q.id AND qas.status='active') assignments
      FROM quizzes q
      WHERE q.tutor_id=? AND q.scope='standalone' AND q.status='published'
      ORDER BY q.created_at DESC`,tutorId);
  const assignments=await all<Assignment>(`SELECT a.id,a.quiz_id,a.student_id,u.name student,a.assigned_at FROM quiz_assignments a JOIN quizzes q ON q.id=a.quiz_id LEFT JOIN users u ON u.id=a.student_id WHERE q.tutor_id=? AND q.scope='standalone' AND a.status='active' ORDER BY a.assigned_at DESC`,tutorId);
  const attempts=await all<Attempt>(`SELECT qa.id,qa.quiz_id,q.title quiz,q.scope,q.kind,qa.student_id,u.name student,qa.answers_json,qa.score,qa.max_score,qa.submitted_at FROM quiz_attempts qa JOIN quizzes q ON q.id=qa.quiz_id JOIN users u ON u.id=qa.student_id WHERE q.tutor_id=? ORDER BY qa.submitted_at DESC LIMIT 100`,tutorId);
  const reviewQuestions=await all<ReviewQuestion>(`SELECT qq.id,qq.quiz_id,qq.prompt,qq.answer_json,qq.position FROM quiz_questions qq JOIN quizzes q ON q.id=qq.quiz_id WHERE q.tutor_id=? ORDER BY qq.quiz_id,qq.position`,tutorId);
  const resetRequests=await all<ResetRequest>(`SELECT r.id,r.quiz_id,q.title quiz,r.learner_id,u.name student,r.reason,r.requested_at FROM assessment_reset_requests r JOIN quizzes q ON q.id=r.quiz_id JOIN users u ON u.id=r.learner_id WHERE q.tutor_id=? AND r.status='pending' ORDER BY r.requested_at`,tutorId);
  return <LmsShell profile={profile} activeRole="tutor" activePath="/dashboard/tutor/quizzes" eyebrow="Independent learner checks" title="Standalone quizzes" subtitle="Create named quizzes outside courses, choose an exact question count, and assign each quiz to one learner or everyone.">
    <Notice params={await searchParams}/>
    <div className="quiz-maker-intro"><div><span>STANDALONE QUIZ WORKFLOW</span><h2>Build, complete, then assign</h2><p>Course quizzes stay inside the course builder. Only independent quizzes appear here.</p></div><ol><li><b>1</b>Name the quiz</li><li><b>2</b>Add the exact question count</li><li><b>3</b>Assign to a student or everyone</li></ol></div>
    <div className="quiz-builder-grid">
      <section className="panel quiz-structure-panel"><div className="panel-head"><div><span className="panel-kicker">YOUR STANDALONE QUIZZES</span><h2>Quiz assignments</h2></div><Status>{quizzes.length} quizzes</Status></div>
        {quizzes.length?quizzes.map(quiz=>{const complete=quiz.questions===quiz.question_count,quizAssignments=assignments.filter(item=>item.quiz_id===quiz.id);return <details className="quiz-admin-card" id={`quiz-${quiz.id}`} key={quiz.id}><summary><div><small>INDEPENDENT QUIZ</small><h3>{quiz.title}</h3><p>{quiz.description}</p><div className="quiz-summary-stats"><span>{quiz.questions} / {quiz.question_count} questions</span><span>{quiz.attempts} completed</span><span>{quiz.assignments} active assignments</span></div></div><Status tone={complete?"green":"amber"}>{complete?"Ready to assign":"Building"}</Status></summary>
          <section className="standalone-quiz-controls"><header><div><small>QUESTION PROGRESS</small><strong>{quiz.questions} of {quiz.question_count} complete</strong></div><progress max={quiz.question_count} value={quiz.questions}/></header>
            {complete?<div className="quiz-assignment-tools"><div><h4>Assign this quiz</h4><p>Every assignment is independent of course enrolments.</p></div><form action="/api/lms" method="post"><input type="hidden" name="action" value="assign-quiz"/><input type="hidden" name="quizId" value={quiz.id}/><input type="hidden" name="target" value="all"/><button>Assign to all students</button></form><form action="/api/lms" method="post"><input type="hidden" name="action" value="assign-quiz"/><input type="hidden" name="quizId" value={quiz.id}/><input type="hidden" name="target" value="student"/><select name="studentId" required><option value="">Choose one student…</option>{students.map(student=><option value={student.id} key={student.id}>{student.name}</option>)}</select><button>Assign student</button></form></div>:<QuizQuestionBuilder quizId={quiz.id} nextPosition={quiz.questions+1} targetCount={quiz.question_count}/>}
            {quizAssignments.length?<div className="active-quiz-assignments"><h4>Active assignments</h4>{quizAssignments.map(item=><article key={item.id}><span><strong>{item.student_id?item.student:"All students"}</strong><small>Assigned {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium"}).format(new Date(item.assigned_at))}</small></span><form action="/api/lms" method="post"><input type="hidden" name="action" value="revoke-quiz"/><input type="hidden" name="assignmentId" value={item.id}/><button>Revoke</button></form></article>)}</div>:null}
            <DeleteButton action="delete-quiz" id={quiz.id} name="quizId" label={`quiz “${quiz.title}”`}/>
          </section>
        </details>}):<div className="empty-module"><h3>No standalone quizzes yet</h3><p>Create the first independent learner quiz using the setup panel.</p></div>}
      </section>
      <aside className="form-card sticky-builder quiz-setup-card"><form action="/api/lms" method="post"><input type="hidden" name="action" value="create-quiz"/><input type="hidden" name="scope" value="standalone"/><span className="panel-kicker">NEW STANDALONE QUIZ</span><h2>Create a named quiz</h2><p>It remains unassigned until every required question has been added.</p><label>Quiz name<input name="title" required maxLength={180} placeholder="Fractions speed check"/></label><label>Student instructions<textarea name="description" rows={4} required placeholder="Explain what this quiz checks and how to complete it."/></label><label>Number of questions<select name="questionCount" defaultValue="5"><option value="5">5 questions</option><option value="10">10 questions</option><option value="15">15 questions</option><option value="20">20 questions</option><option value="25">25 questions</option></select></label><button>Create quiz & add questions →</button></form></aside>
    </div>
    {resetRequests.length?<section className="panel assessment-reset-panel"><div className="panel-head"><div><span className="panel-kicker">RE-ATTEMPT REQUESTS</span><h2>Final assessment approvals</h2></div><Status tone="amber">{resetRequests.length} pending</Status></div><div>{resetRequests.map(request=><article key={request.id}><div><strong>{request.student}</strong><span>{request.quiz}</span><p>{request.reason}</p><small>Requested {new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(request.requested_at))}</small></div><form action="/api/lms" method="post"><input type="hidden" name="action" value="approve-assessment-reset"/><input type="hidden" name="requestId" value={request.id}/><input type="hidden" name="quizId" value={request.quiz_id}/><input type="hidden" name="learnerId" value={request.learner_id}/><button>Approve re-attempt</button></form></article>)}</div></section>:null}
    <section className="panel quiz-results-review"><div className="panel-head"><div><span className="panel-kicker">STUDENT-WISE REVIEW</span><h2>Quiz & assessment results</h2><p>Course checks remain inside their courses; this consolidated view is for reviewing learner answers.</p></div><Status>{attempts.length} attempts</Status></div><div>{attempts.map(attempt=>{let answers:Record<string,string>={};try{answers=JSON.parse(attempt.answers_json)as Record<string,string>;}catch{answers={};}const questions=reviewQuestions.filter(question=>question.quiz_id===attempt.quiz_id);return <details key={attempt.id}><summary><span><strong>{attempt.student}</strong><small>{attempt.scope==="course"?"COURSE":"STANDALONE"} · {attempt.kind.replaceAll("_"," ")}</small></span><span><b>{attempt.max_score?Math.round(attempt.score*100/attempt.max_score):0}%</b><small>{attempt.quiz}</small></span><time>{new Intl.DateTimeFormat("en-IN",{dateStyle:"medium",timeStyle:"short"}).format(new Date(attempt.submitted_at))}</time></summary><div className="attempt-answer-list">{questions.map((question,index)=>{let correct="";try{correct=String(JSON.parse(question.answer_json));}catch{correct=question.answer_json;}const given=answers[question.id]??"";return <article key={question.id}><span>{index+1}</span><div><MathText text={question.prompt}/><small>Student: <b>{given||"No answer"}</b></small><small>Correct: <b>{correct}</b></small></div></article>})}</div>{attempt.kind==="final_assessment"?<form className="manual-reset-form" action="/api/lms" method="post"><input type="hidden" name="action" value="reset-assessment-attempt"/><input type="hidden" name="quizId" value={attempt.quiz_id}/><input type="hidden" name="learnerId" value={attempt.student_id}/><button>Reset final assessment attempt</button></form>:null}</details>})}{!attempts.length?<p className="empty-copy">Student attempts will appear here with every submitted and correct answer.</p>:null}</div></section>
  </LmsShell>;
}

