import { getChatGPTUser } from "@/app/chatgpt-auth";
import { callViyu, getViyuSettings } from "../provider";
import { createId, database, ensureProfile } from "@/db/lms";
import { NextResponse } from "next/server";

type Question={type?:string;prompt?:string;options?:string[];answer?:string;points?:number};
type Quiz={title?:string;description?:string;questions?:Question[]};
type Lesson={title?:string;summary?:string;content?:string;durationMinutes?:number};
type Chapter={title?:string;description?:string;lessons?:Lesson[];assignment?:{title?:string;instructions?:string;points?:number};practiceQuiz?:Quiz;assessment?:Quiz};
type GeneratedCourse={title?:string;subject?:string;level?:string;description?:string;chapters?:Chapter[];finalAssessment?:Quiz};
const clean=(value:unknown,max=4000)=>String(value??"").trim().slice(0,max);
const list=<T,>(value:unknown,max:number)=>Array.isArray(value)?value.slice(0,max) as T[]:[];
function jsonFrom(text:string){const cleaned=text.replace(/^```(?:json)?\s*/i,"").replace(/```\s*$/i,"");const start=cleaned.indexOf("{");const end=cleaned.lastIndexOf("}");if(start<0||end<=start)throw new Error("VIYU could not structure this course. Add the learner level, topic and duration, then try again.");return JSON.parse(cleaned.slice(start,end+1)) as GeneratedCourse;}

export async function POST(request:Request){
  const identity=await getChatGPTUser();if(!identity)return NextResponse.json({error:"Authentication required"},{status:401});
  const profile=await ensureProfile(identity);if(!['admin','tutor'].includes(profile.role))return NextResponse.json({error:"Course authoring access required"},{status:403});
  const input=await request.json() as {prompt?:string};const prompt=clean(input.prompt,6000);if(prompt.length<12)return NextResponse.json({error:"Describe the subject, learner level, goals and preferred course length."},{status:400});
  const settings=await getViyuSettings();if(!settings?.enabled)return NextResponse.json({error:"VIYU is not enabled yet."},{status:503});
  const system=`You are VIYU's course-generation engine for Skillvelop, a live 1:1 LMS. Return JSON only with this exact shape: {"title":"","subject":"","level":"","description":"","chapters":[{"title":"","description":"","lessons":[{"title":"","summary":"","content":"","durationMinutes":30}],"assignment":{"title":"","instructions":"","points":100},"practiceQuiz":{"title":"","description":"","questions":[{"type":"mcq","prompt":"","options":["","","",""],"answer":"","points":10}]},"assessment":{"title":"","description":"","questions":[...]} }],"finalAssessment":{"title":"","description":"","questions":[...]}}. Create 4 to 8 chapters, 3 to 5 substantial lessons per chapter, one meaningful assignment, one practice quiz and one scored assessment per chapter, plus a cumulative final assessment. Include 4 to 8 varied questions in every quiz. Question type must be one of mcq, fill_blank, one_word, order, matching, drag_drop. For order/drag_drop options are the correctly ordered items and answer joins them with |. For matching options use Left=Right and answer joins pairs with |. Use LaTeX in $ delimiters for mathematics. Make lesson content complete enough to teach from, age-appropriate, accessible, and designed for live 1:1 instruction. ${settings.system_guidance}`;
  try{
    const raw=await callViyu(settings,system,[{role:"user",body:prompt}],7500);const generated=jsonFrom(raw);const chapters=list<Chapter>(generated.chapters,8);if(chapters.length<1)throw new Error("VIYU did not return any chapters. Please try a more specific prompt.");
    const db=database();const tutorId=profile.role==='admin'?'usr_demo_tutor':profile.id;const courseId=createId("crs"),now=new Date().toISOString();const statements:D1PreparedStatement[]=[];
    const title=clean(generated.title,160)||"VIYU generated course",subject=clean(generated.subject,100)||"General",level=clean(generated.level,100)||"Personalised",description=clean(generated.description,1200)||`A complete personalised course created from: ${prompt.slice(0,500)}`;
    statements.push(db.prepare("INSERT INTO courses (id,title,subject,level,description,cover_image_url,is_unlocked,tutor_id,status,accent,created_at) VALUES (?,?,?,?,?,'',0,?,'active','coral',?)").bind(courseId,title,subject,level,description,tutorId,now));
    let lessonCount=0,quizCount=0,questionCount=0,activityCount=0;
    const addQuiz=(chapterId:string,quiz:Quiz|undefined,kind:"quiz"|"assessment"|"final_assessment",fallback:string)=>{const quizId=createId("qz"),quizTitle=clean(quiz?.title,180)||fallback,questions=list<Question>(quiz?.questions,10);statements.push(db.prepare("INSERT INTO quizzes (id,course_id,chapter_id,tutor_id,title,description,kind,attempt_limit,is_unlocked,status,created_at) VALUES (?,?,?,?,?,?,?,?,0,'published',?)").bind(quizId,courseId,chapterId,tutorId,quizTitle,clean(quiz?.description,1000)||"Tutor-reviewed VIYU knowledge check.",kind,kind==='quiz'?3:1,now));quizCount++;questions.forEach((question,index)=>{const type=['mcq','fill_blank','drag_drop','order','matching','one_word'].includes(clean(question.type,30))?clean(question.type,30):'mcq';const options=list<string>(question.options,20).map(item=>clean(item,500)).filter(Boolean);const answer=clean(question.answer,2000).toLowerCase();if(!clean(question.prompt,4000)||!answer)return;statements.push(db.prepare("INSERT INTO quiz_questions (id,quiz_id,type,prompt,options_json,answer_json,points,position,image_r2_key,image_file_name,image_content_type,image_size_bytes) VALUES (?,?,?,?,?,?,?,?,\'\',\'\',\'\',0)").bind(createId("qq"),quizId,type,clean(question.prompt,4000),JSON.stringify(options),JSON.stringify(answer),Math.max(1,Math.min(100,Number(question.points)||10)),index+1));questionCount++;});};
    chapters.forEach((chapter,index)=>{const chapterId=createId("chp");statements.push(db.prepare("INSERT INTO chapters (id,course_id,tutor_id,title,description,position,is_unlocked,created_at) VALUES (?,?,?,?,?,?,0,?)").bind(chapterId,courseId,tutorId,clean(chapter.title,180)||`Chapter ${index+1}`,clean(chapter.description,1000),index+1,now));list<Lesson>(chapter.lessons,6).forEach((lesson,lessonIndex)=>{const title=clean(lesson.title,180),summary=clean(lesson.summary,1000),content=clean(lesson.content,12000);if(!title||!content)return;statements.push(db.prepare("INSERT INTO lessons (id,course_id,chapter_id,tutor_id,title,summary,content,video_url,position,duration_minutes,is_unlocked,status,created_at) VALUES (?,?,?,?,?,?,?,'',?,?,0,'published',?)").bind(createId("les"),courseId,chapterId,tutorId,title,summary||title,content,lessonIndex+1,Math.max(10,Math.min(180,Number(lesson.durationMinutes)||30)),now));lessonCount++;});const assignment=chapter.assignment;if(assignment){const due=new Date(Date.now()+(index+1)*7*86400000).toISOString();statements.push(db.prepare("INSERT INTO activities (id,course_id,chapter_id,tutor_id,title,type,instructions,due_at,points,is_unlocked,status,created_at) VALUES (?,?,?,?,?,'assignment',?,?,?,0,'published',?)").bind(createId("act"),courseId,chapterId,tutorId,clean(assignment.title,180)||`${clean(chapter.title,120)} assignment`,clean(assignment.instructions,5000)||"Complete the chapter application task.",due,Math.max(10,Math.min(1000,Number(assignment.points)||100)),now));activityCount++;}addQuiz(chapterId,chapter.practiceQuiz,'quiz',`${clean(chapter.title,120)} practice quiz`);addQuiz(chapterId,chapter.assessment,'assessment',`${clean(chapter.title,120)} assessment`);if(index===chapters.length-1)addQuiz(chapterId,generated.finalAssessment,'final_assessment',`${title} final assessment`);});
    await db.batch(statements);return NextResponse.json({courseId,title,chapters:chapters.length,lessons:lessonCount,quizzes:quizCount,questions:questionCount,activities:activityCount,href:`/dashboard/tutor/curriculum?course=${courseId}`});
  }catch(cause){return NextResponse.json({error:cause instanceof Error?cause.message:"VIYU could not create this course."},{status:502});}
}
