"use client";

import { useState } from "react";
import { Bot, BookOpenCheck, Send, Sparkles, UserRound } from "lucide-react";
import ViyuRichText from "./ViyuRichText";

type Course={id:string;title:string};
type Message={role:"user"|"assistant";body:string};
type BuildResult={title:string;chapters:number;lessons:number;quizzes:number;questions:number;activities:number;href:string};

export default function AIAssistant({mode,courses=[],enabled}:{mode:"authoring"|"student";courses?:Course[];enabled:boolean}){
  const [courseId,setCourseId]=useState(courses[0]?.id??"");const [message,setMessage]=useState("");const [messages,setMessages]=useState<Message[]>([]);const [threadId,setThreadId]=useState("");const [busy,setBusy]=useState(false);const [building,setBuilding]=useState(false);const [error,setError]=useState("");const [build,setBuild]=useState<BuildResult|null>(null);
  const suggestions=mode==="student"?["Explain this idea in a simpler way","Give me a hint without revealing the answer","Help me find the mistake in my working"]:["Design a four-chapter course blueprint","Create an engaging lesson sequence","Build an assessment rubric and quiz bank"];
  async function ask(text=message){const prompt=text.trim();if(!prompt||busy||building)return;setError("");setMessages(items=>[...items,{role:"user",body:prompt}]);setMessage("");setBusy(true);try{const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode,message:prompt,courseId:mode==="student"?courseId:undefined,threadId:threadId||undefined})});const payload=await response.json() as {answer?:string;threadId?:string;error?:string};if(!response.ok)throw new Error(payload.error||"VIYU could not respond.");setThreadId(payload.threadId??threadId);setMessages(items=>[...items,{role:"assistant",body:payload.answer??""}]);}catch(cause){setError(cause instanceof Error?cause.message:"VIYU is unavailable.");}finally{setBusy(false);}}
  async function buildCourse(){const prompt=message.trim();if(!prompt||busy||building)return;setError("");setBuild(null);setBuilding(true);try{const response=await fetch("/api/ai/generate-course",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({prompt})});const payload=await response.json() as BuildResult&{error?:string};if(!response.ok)throw new Error(payload.error||"VIYU could not create this course.");setBuild(payload);setMessage("");}catch(cause){setError(cause instanceof Error?cause.message:"VIYU could not create this course.");}finally{setBuilding(false);}}
  return <section className="ai-studio">
    <header><div className="ai-orb"><Sparkles size={24}/></div><div><span>VIYU · SKILLVELOP INTELLIGENCE</span><h2>{mode==="student"?"Your personal doubt coach":"Your complete course studio"}</h2><p>{mode==="student"?"Clarify doubts using your unlocked lessons. VIYU guides your thinking without doing assessed work for you.":"Describe a course once and VIYU can create its complete chapter, lesson, assignment, quiz and assessment structure inside the LMS."}</p></div><span className={enabled?"ai-live":"ai-offline"}>{enabled?"VIYU ready":"Setup required"}</span></header>
    {mode==="student"&&<label className="ai-course-select">Learning context<select value={courseId} onChange={event=>setCourseId(event.target.value)}>{courses.map(course=><option value={course.id} key={course.id}>{course.title}</option>)}</select></label>}
    <div className="ai-suggestions">{suggestions.map(item=><button type="button" onClick={()=>{setMessage(item);if(mode==="student")ask(item);}} disabled={!enabled||busy||building} key={item}>{item}</button>)}</div>
    <div className="ai-thread" aria-live="polite">{messages.length?messages.map((item,index)=><article className={`ai-message ${item.role}`} key={index}><span>{item.role==="assistant"?<Bot size={18}/>:<UserRound size={18}/>}</span><div><small>{item.role==="assistant"?"VIYU":"You"}</small>{item.role==="assistant"?<ViyuRichText text={item.body}/>:<p>{item.body}</p>}</div></article>):<div className="ai-empty"><Bot size={28}/><strong>{mode==="student"?"What would you like to understand?":"What complete course should VIYU create?"}</strong><p>{mode==="student"?"Choose your course, then explain the exact point that is confusing.":"Include subject, learner age or level, outcome, duration and any curriculum standard in one prompt."}</p></div>}{busy&&<article className="ai-message assistant thinking"><span><Bot size={18}/></span><div><small>VIYU</small><p>Thinking through the clearest learning support…</p></div></article>}{building&&<div className="viyu-build-progress"><span><BookOpenCheck size={22}/></span><div><strong>VIYU is building the complete course</strong><p>Creating chapters, full lessons, assignments, practice quizzes and assessments. This can take a minute.</p></div></div>}{build&&<div className="viyu-build-result"><BookOpenCheck size={26}/><div><span>COMPLETE COURSE CREATED</span><h3>{build.title}</h3><p>{build.chapters} chapters · {build.lessons} lessons · {build.quizzes} quizzes and assessments · {build.questions} questions · {build.activities} assignments</p><a href={build.href}>Review and unlock the course →</a></div></div>}</div>
    {error&&<div className="ai-error" role="alert">{error}</div>}
    <form className="ai-composer" onSubmit={event=>{event.preventDefault();ask();}}><textarea value={message} onChange={event=>setMessage(event.target.value)} rows={4} disabled={!enabled||busy||building} placeholder={mode==="student"?"Describe your doubt and show what you have tried…":"Example: Create a 12-week Grade 7 mathematics course for a visual learner, with four chapters, live 1:1 activities and Cambridge-aligned assessments…"}/><div className="ai-composer-actions"><button disabled={!enabled||busy||building||!message.trim()} aria-label="Ask VIYU"><Send size={19}/><span>{mode==="student"?"Clarify my doubt":"Plan with VIYU"}</span></button>{mode==="authoring"&&<button className="viyu-build-button" type="button" onClick={buildCourse} disabled={!enabled||busy||building||!message.trim()}><BookOpenCheck size={19}/><span>Create complete course</span></button>}</div></form>
    <footer><span>VIYU can make mistakes. Tutors and admins review generated content before unlocking it.</span>{mode==="student"&&<span>VIYU is limited to doubt clarification and will not reveal assessment answers.</span>}</footer>
  </section>;
}
