"use client";

import { Bot, Send, Sparkles, X } from "lucide-react";
import { useState } from "react";
import MathText from "./MathText";

type Message={role:"user"|"assistant";body:string};
export default function CourseAIFloat({courseId,chapterId,lessonId,contextLabel,placement="floating"}:{courseId:string;chapterId?:string|null;lessonId?:string;contextLabel:string;placement?:"floating"|"topbar"}){
  const [open,setOpen]=useState(false),[message,setMessage]=useState(""),[messages,setMessages]=useState<Message[]>([]),[threadId,setThreadId]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(event:React.FormEvent){event.preventDefault();const prompt=message.trim();if(!prompt||busy)return;setMessages(items=>[...items,{role:"user",body:prompt}]);setMessage("");setBusy(true);setError("");try{const response=await fetch("/api/ai",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({mode:"student",message:prompt,courseId,chapterId:chapterId||undefined,lessonId,threadId:threadId||undefined})});const payload=await response.json() as {answer?:string;threadId?:string;error?:string};if(!response.ok)throw new Error(payload.error||"VIYU could not respond.");setThreadId(payload.threadId??threadId);setMessages(items=>[...items,{role:"assistant",body:payload.answer??""}]);}catch(cause){setError(cause instanceof Error?cause.message:"VIYU is unavailable.");}finally{setBusy(false);}}
  const classes=["course-ai-float",placement==="topbar"?"topbar":"",open?"open":""].filter(Boolean).join(" ");
  return <div className={classes}><button className="course-ai-trigger" type="button" onClick={()=>setOpen(value=>!value)} aria-label={open?"Close AI doubt assistant":"Open AI doubt assistant"} aria-expanded={open}>{open?<X size={20}/>:<><Sparkles size={18}/><span>Ask VIYU</span></>}</button>{open&&<section className="course-ai-panel"><header><span><Bot size={20}/></span><div><strong>VIYU doubt assistant</strong><small>{contextLabel}</small></div><i>PAID</i></header><div className="course-ai-thread">{messages.length?messages.map((item,index)=><article className={item.role} key={index}><small>{item.role==='assistant'?'VIYU':'You'}</small><MathText text={item.body}/></article>):<div className="course-ai-welcome"><Sparkles size={24}/><strong>Ask about what you are learning here</strong><p>I can clarify this course content with hints and examples. I cannot answer questions outside your Skillvelop curriculum.</p></div>}{busy&&<article className="assistant"><small>VIYU</small><p>Thinking within this lesson…</p></article>}</div>{error&&<p className="course-ai-error">{error}</p>}<form onSubmit={submit}><textarea rows={3} value={message} onChange={event=>setMessage(event.target.value)} placeholder="What would you like clarified?" maxLength={6000}/><button disabled={busy||!message.trim()} aria-label="Send doubt"><Send size={18}/></button></form><footer>Curriculum-only help · no assessment answers</footer></section>}</div>;
}

