import type { CSSProperties } from "react";
import { Activity, BrainCircuit, ChartPie, TrendingUp } from "lucide-react";

type Axis={label:string;value:number};
const clamp=(value:number)=>Math.max(0,Math.min(100,Math.round(value||0)));
function polygon(values:number[],scale=1){const count=values.length;return values.map((value,index)=>{const angle=-Math.PI/2+(Math.PI*2*index)/count,r=clamp(value)/100*88*scale;return `${100+Math.cos(angle)*r},${100+Math.sin(angle)*r}`;}).join(" ");}
export function RadarChart({axes}:{axes:Axis[]}){const safe=axes.slice(0,6);return <div className="radar-chart"><svg viewBox="0 0 200 200" role="img" aria-label={safe.map(axis=>`${axis.label} ${clamp(axis.value)} percent`).join(", ")}><title>Performance radar chart</title>{[.25,.5,.75,1].map(level=><polygon className="radar-grid-line" points={polygon(safe.map(()=>100),level)} key={level}/>)}{safe.map((_,index)=>{const angle=-Math.PI/2+(Math.PI*2*index)/safe.length;return <line className="radar-axis" x1="100" y1="100" x2={100+Math.cos(angle)*88} y2={100+Math.sin(angle)*88} key={index}/>})}<polygon className="radar-data" points={polygon(safe.map(axis=>axis.value))}/>{safe.map((axis,index)=>{const angle=-Math.PI/2+(Math.PI*2*index)/safe.length,r=88*clamp(axis.value)/100;return <circle className="radar-point" cx={100+Math.cos(angle)*r} cy={100+Math.sin(angle)*r} r="4" key={axis.label}/>})}</svg><div className="radar-legend">{safe.map(axis=><span key={axis.label}><i/>{axis.label}<strong>{clamp(axis.value)}%</strong></span>)}</div></div>}
export function DonutChart({value,label,note}:{value:number;label:string;note:string}){const safe=clamp(value);return <div className="donut-insight"><div className="donut-ring" style={{"--donut-value":`${safe*3.6}deg`} as CSSProperties}><span><strong>{safe}%</strong><small>{label}</small></span></div><p>{note}</p></div>}
export function TrendBars({values}:{values:number[]}){const safe=values.slice(-8);return <div className="trend-bars" aria-label={`Recent trend: ${safe.join(", ")}`}><div>{safe.map((value,index)=><i style={{"--bar":`${Math.max(10,clamp(value))}%`} as CSSProperties} key={index}/>)}</div><span>Earlier</span><span>Current</span></div>}
export default function DashboardInsights({eyebrow,title,subtitle,axes,donutValue,donutLabel,donutNote,trend}:{eyebrow:string;title:string;subtitle:string;axes:Axis[];donutValue:number;donutLabel:string;donutNote:string;trend:number[]}){return <section className="insights-panel"><header><div><span>{eyebrow}</span><h2>{title}</h2><p>{subtitle}</p></div><div className="live-insight"><Activity size={17}/><span>Live insights</span></div></header><div className="insight-grid"><article><div className="insight-title"><BrainCircuit size={20}/><div><strong>Performance web</strong><small>Balanced view across key outcomes</small></div></div><RadarChart axes={axes}/></article><article><div className="insight-title"><ChartPie size={20}/><div><strong>{donutLabel}</strong><small>Current operational ratio</small></div></div><DonutChart value={donutValue} label={donutLabel} note={donutNote}/></article><article><div className="insight-title"><TrendingUp size={20}/><div><strong>Momentum</strong><small>Recent activity pattern</small></div></div><TrendBars values={trend}/></article></div></section>}
