import { LmsShell, Notice } from "../../../components";
import { requireAdminPermission } from "../../../auth";

export default async function Page({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const profile = await requireAdminPermission("manage_users", "/dashboard/admin/users/new");
  return <LmsShell profile={profile} activeRole="admin" activePath="/dashboard/admin/users" eyebrow="People & access" title="Create a user or manager" subtitle="Add a person and control exactly which parts of Skillvelop they can operate." actions={<a className="module-link secondary" href="/dashboard/admin/users">← All users</a>}>
    <Notice params={await searchParams}/><div className="form-page"><section className="form-card"><form action="/api/lms" method="post"><input type="hidden" name="action" value="create-user"/><label>Full name<input name="name" required placeholder="e.g. Neha Sharma"/></label><label>Email address<input type="email" name="email" required placeholder="name@example.com"/></label><label>Login username<input name="username" required minLength={4} pattern="[A-Za-z0-9._-]+" autoComplete="off" placeholder="e.g. neha-sharma"/></label><label>Temporary password<input type="password" name="temporaryPassword" required minLength={8} autoComplete="new-password" placeholder="Minimum 8 characters"/></label><label>Workspace role<select name="role" defaultValue="student"><option value="student">Student</option><option value="tutor">Tutor</option>{profile.role==='admin'&&<><option value="manager">Manager (custom access)</option><option value="admin">Full administrator</option></>}</select></label>{profile.role==='admin'&&<fieldset className="permission-set"><legend>Manager permissions</legend><label><input type="checkbox" name="permissions" value="view_dashboard"/> View admin overview</label><label><input type="checkbox" name="permissions" value="manage_users"/> Manage users</label><label><input type="checkbox" name="permissions" value="manage_students"/> Manage students and plans</label><label><input type="checkbox" name="permissions" value="manage_courses"/> Manage courses</label><label><input type="checkbox" name="permissions" value="manage_classes"/> Manage live classes</label><small>These permissions apply only when Manager is selected.</small></fieldset>}<button>Create user →</button></form></section><aside className="help-card"><h3>Manager vs administrator</h3><p>A manager receives only the modules you select. A full administrator has unrestricted platform access, including creating other managers.</p><p>Share the username and temporary password privately. The account becomes active immediately.</p></aside></div>
  </LmsShell>;
}
