import { all } from "@/db/lms";
import { BookOpen, ClipboardList, FileQuestion, FolderPlus, LibraryBig, Upload } from "lucide-react";
import { LmsShell, Notice } from "../../components";
import { requireRole } from "../../auth";
import { MathFormField } from "../../MathComposer";
import LessonAuthoringForm from "./LessonAuthoringForm";
import QuizQuestionBuilder from "../quizzes/QuizQuestionBuilder";
import DeleteButton from "../../DeleteButton";
import AuthoringModal from "./AuthoringModal";
import { DateTimePicker12 } from "@/app/components/DateTimePicker12";

type Course={id:string;title:string;description:string;is_unlocked:number;course_mode:string;completion_points:number};
type Chapter={id:string;course_id:string;title:string;description:string;position:number;is_unlocked:number;release_mode:string;drip_days:number};
type Lesson={id:string;course_id:string;chapter_id:string|null;title:string;summary:string;content:string;position:number;duration_minutes:number;is_unlocked:number};
type Quiz={id:string;course_id:string;chapter_id:string|null;title:string;description:string;kind:string;is_unlocked:number;question_count:number;questions:number;passing_percentage:number;attempt_limit:number};
type Activity={id:string;course_id:string;chapter_id:string|null;title:string;instructions:string;type:string;due_at:string;points:number;is_unlocked:number};
export const dynamic="force-dynamic";

function Toggle({entity,id,open}:{entity:string;id:string;open:number}){return <form className="mini-unlock" action="/api/lms" method="post"><input type="hidden" name="action" value="set-content-unlock"/><input type="hidden" name="entity" value={entity}/><input type="hidden" name="id" value={id}/><input type="hidden" name="next" value={open?"0":"1"}/><input type="hidden" name="returnTo" value="/dashboard/tutor/curriculum?updated=unlock"/><button>{open?"🔓 Unlocked":"🔒 Locked"}</button></form>}
function CourseOptions({courses}:{courses:Course[]}){return <>{courses.map(course=><option key={course.id} value={course.id}>{course.title} · {course.course_mode==="self_paced"?"Self-paced":"Guided"}</option>)}</>}
function ChapterOptions({courses,chapters}:{courses:Course[];chapters:Chapter[]}){return <>{chapters.map(chapter=><option key={chapter.id} value={chapter.id}>{courses.find(course=>course.id===chapter.course_id)?.title} · Ch {chapter.position}: {chapter.title}</option>)}</>}

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole("tutor","/dashboard/tutor/curriculum"),tutorId=profile.id;
  const courses=profile.role==="admin"?await all<Course>("SELECT id,title,description,is_unlocked,course_mode,completion_points FROM courses WHERE status='active' ORDER BY title"):await all<Course>("SELECT id,title,description,is_unlocked,course_mode,completion_points FROM courses WHERE tutor_id=? AND creator_role='tutor' AND creator_id=? AND status='active' ORDER BY title",tutorId,tutorId);
  const hasCourses=courses.length>0;
  const chapters=hasCourses?profile.role==="admin"?await all<Chapter>("SELECT id,course_id,title,description,position,is_unlocked,release_mode,drip_days FROM chapters WHERE course_id IN (SELECT id FROM courses WHERE status='active') ORDER BY course_id,position"):await all<Chapter>("SELECT ch.id,ch.course_id,ch.title,ch.description,ch.position,ch.is_unlocked,ch.release_mode,ch.drip_days FROM chapters ch JOIN courses c ON c.id=ch.course_id WHERE c.tutor_id=? AND c.creator_role='tutor' AND c.creator_id=? ORDER BY ch.course_id,ch.position",tutorId,tutorId):[];
  const lessons=hasCourses?profile.role==="admin"?await all<Lesson>("SELECT id,course_id,chapter_id,title,summary,content,position,duration_minutes,is_unlocked FROM lessons WHERE course_id IN (SELECT id FROM courses WHERE status='active') ORDER BY course_id,chapter_id,position"):await all<Lesson>("SELECT l.id,l.course_id,l.chapter_id,l.title,l.summary,l.content,l.position,l.duration_minutes,l.is_unlocked FROM lessons l JOIN courses c ON c.id=l.course_id WHERE c.tutor_id=? AND c.creator_role='tutor' AND c.creator_id=? ORDER BY l.course_id,l.chapter_id,l.position",tutorId,tutorId):[];
  const quizzes=hasCourses?profile.role==="admin"?await all<Quiz>("SELECT q.id,q.course_id,q.chapter_id,q.title,q.description,q.kind,q.is_unlocked,q.question_count,q.passing_percentage,q.attempt_limit,COUNT(qq.id) questions FROM quizzes q LEFT JOIN quiz_questions qq ON qq.quiz_id=q.id WHERE q.scope='course' AND q.status='published' GROUP BY q.id ORDER BY q.course_id,q.chapter_id,q.created_at"):await all<Quiz>("SELECT q.id,q.course_id,q.chapter_id,q.title,q.description,q.kind,q.is_unlocked,q.question_count,q.passing_percentage,q.attempt_limit,COUNT(qq.id) questions FROM quizzes q JOIN courses c ON c.id=q.course_id LEFT JOIN quiz_questions qq ON qq.quiz_id=q.id WHERE c.tutor_id=? AND c.creator_role='tutor' AND c.creator_id=? AND q.scope='course' AND q.status='published' GROUP BY q.id ORDER BY q.course_id,q.chapter_id,q.created_at",tutorId,tutorId):[];
  const activities=hasCourses?profile.role==="admin"?await all<Activity>("SELECT id,course_id,chapter_id,title,instructions,type,due_at,points,is_unlocked FROM activities WHERE course_id IN (SELECT id FROM courses WHERE status='active') AND status!='closed' ORDER BY course_id,chapter_id,due_at"):await all<Activity>("SELECT a.id,a.course_id,a.chapter_id,a.title,a.instructions,a.type,a.due_at,a.points,a.is_unlocked FROM activities a JOIN courses c ON c.id=a.course_id WHERE c.tutor_id=? AND c.creator_role='tutor' AND c.creator_id=? AND a.status!='closed' ORDER BY a.course_id,a.chapter_id,a.due_at",tutorId,tutorId):[];

  const createChapter=<form action="/api/lms" method="post"><input type="hidden" name="action" value="create-chapter"/><label>Course<select name="courseId" required><option value="">Choose course</option><CourseOptions courses={courses}/></select></label><div className="form-row"><label>Chapter number<input name="position" type="number" min="1" defaultValue="1"/></label><label>Release model<select name="releaseMode"><option value="free">Free access</option><option value="drip">Drip release (guided only)</option></select></label></div><label>Chapter title<input name="title" required placeholder="Chapter 1: Foundations"/></label><label>Description<textarea name="description" rows={4} placeholder="What will the learner understand and practise?"/></label><label>Release after days<input name="dripDays" type="number" min="1" max="3650" defaultValue="7"/><small>Only used by guided courses with drip release.</small></label><label className="check-row"><input type="checkbox" name="isUnlocked"/> Unlock now (guided courses)</label><button>Add chapter →</button></form>;
  const createQuiz=<form action="/api/lms" method="post"><input type="hidden" name="action" value="create-quiz"/><input type="hidden" name="scope" value="course"/><input type="hidden" name="returnTo" value="/dashboard/tutor/curriculum?created=quiz"/><label>Course<select name="courseId" required><option value="">Choose course</option><CourseOptions courses={courses}/></select></label><label>Chapter<select name="chapterId" required><option value="">Choose chapter</option><ChapterOptions courses={courses} chapters={chapters}/></select></label><label>Type<select name="kind"><option value="quiz">Practice quiz</option><option value="assessment">Assessment</option><option value="final_assessment">Final assessment</option></select></label><MathFormField name="title" label="Title" required compact/><MathFormField name="description" label="Instructions" required multiline compact/><div className="form-row"><label>Questions<select name="questionCount" defaultValue="5"><option value="5">5</option><option value="10">10</option><option value="15">15</option><option value="20">20</option><option value="25">25</option></select></label><label>Pass mark (%)<input name="passingPercentage" type="number" min="0" max="100" defaultValue="60"/></label></div><label>Attempts<input name="attemptLimit" type="number" min="1" max="10" defaultValue="3"/><small>Self-paced assessments can use multiple attempts. Guided assessments use one.</small></label><button>Create knowledge check →</button></form>;
  const createActivity=<form action="/api/lms" method="post"><input type="hidden" name="action" value="create-activity"/><input type="hidden" name="returnTo" value="/dashboard/tutor/curriculum?created=activity"/><label>Course<select name="courseId" required><option value="">Choose course</option><CourseOptions courses={courses}/></select></label><label>Chapter<select name="chapterId" required><option value="">Choose chapter</option><ChapterOptions courses={courses} chapters={chapters}/></select></label><label>Work type<select name="type"><option value="assignment">Assignment</option><option value="homework">Homework</option><option value="classwork">Class work</option><option value="assessment">Assessment task</option></select></label><MathFormField name="title" label="Title" required compact/><MathFormField name="instructions" label="Instructions" required multiline/><div className="form-row schedule-row"><DateTimePicker12 name="dueAt" label="Due date and time" required/><label>Points<input name="points" type="number" min="1" max="1000" defaultValue="100"/></label></div><label className="check-row"><input type="checkbox" name="isUnlocked"/> Unlock now (guided courses)</label><button>Publish work →</button></form>;
  const uploadResource=<form action="/api/lms" method="post" encType="multipart/form-data"><input type="hidden" name="action" value="upload-lesson-resource"/><label>Lesson<select name="lessonId" required><option value="">Choose lesson</option>{lessons.map(lesson=><option key={lesson.id} value={lesson.id}>{lesson.title}</option>)}</select></label><label>Display title<input name="title"/></label><label>Learning file<input name="file" type="file" accept=".pdf,.ppt,.pptx,.odp,.zip,.doc,.docx,.odt,.rtf,.txt,.csv,.xls,.xlsx,.ods,image/*,video/*,audio/*" required/><small>Images, video, audio, SCORM ZIP, presentations and common documents are supported.</small></label><button>Upload resource →</button></form>;

  return <LmsShell profile={profile} activeRole="tutor" activePath="/dashboard/tutor/curriculum" eyebrow="Course builder" title="Build the classroom without the scrolling" subtitle="Launch a focused workspace for each task, then review, edit or remove every item directly from the course structure.">
    <Notice params={await searchParams}/>
    <section className="builder-action-hub"><header><div><span className="panel-kicker">QUICK CREATE</span><h2>What would you like to add?</h2><p>Each tool opens in a spacious builder window and keeps your place in the course structure.</p></div><LibraryBig size={28}/></header><div className="builder-launch-grid">
      <AuthoringModal title="Create a chapter" description="Organise the learning path and choose the release model." buttonLabel="Chapter">{createChapter}</AuthoringModal>
      <AuthoringModal title="Create a lesson" description="Build rich content with maths, files, video, SCORM, documents, iframe embeds and games." buttonLabel="Lesson"><LessonAuthoringForm courses={courses} chapters={chapters}/></AuthoringModal>
      <AuthoringModal title="Create a quiz or assessment" description="Choose the question count, pass mark and attempt policy." buttonLabel="Quiz / assessment">{createQuiz}</AuthoringModal>
      <AuthoringModal title="Create an assignment" description="Set learner instructions, due time and points." buttonLabel="Assignment">{createActivity}</AuthoringModal>
      <AuthoringModal title="Add a lesson resource" description="Attach a downloadable or embedded learning file to an existing lesson." buttonLabel="Resource">{uploadResource}</AuthoringModal>
    </div></section>

    <div className="builder-workflow"><span>1 · Choose a course</span><span>2 · Create with a popup</span><span>3 · Review and edit in place</span><span>4 · Learners progress in sequence</span></div>
    <section className="course-tree">{courses.map(course=>{const selfPaced=course.course_mode==="self_paced",courseChapters=chapters.filter(chapter=>chapter.course_id===course.id);return <article className="course-tree-card" key={course.id}>
      <header><div><small>{selfPaced?"SELF-PACED PATHWAY":"GUIDED CLASSROOM"}</small><h2>{course.title}</h2><p>{courseChapters.length} chapters · {lessons.filter(item=>item.course_id===course.id).length} lessons · {quizzes.filter(item=>item.course_id===course.id).length} quizzes/assessments</p></div><div className="tree-item-actions course-actions"><AuthoringModal title={`Review ${course.title}`} description="Update the course identity, delivery model and completion reward." buttonLabel="Edit course" variant="edit" compact><form action="/api/lms" method="post"><input type="hidden" name="action" value="update-course"/><input type="hidden" name="courseId" value={course.id}/><label>Course name<input name="title" required defaultValue={course.title}/></label><label>Description<textarea name="description" rows={5} required defaultValue={course.description}/></label><div className="form-row"><label>Delivery model<select name="courseMode" defaultValue={course.course_mode}><option value="guided">Guided classroom</option><option value="self_paced">Self-paced sequence</option></select></label><label>Completion points<input name="completionPoints" type="number" min="0" max="100000" defaultValue={course.completion_points}/></label></div><button>Save course changes</button></form></AuthoringModal>{selfPaced?<span className="auto-sequence-badge">Auto sequence</span>:<Toggle entity="course" id={course.id} open={course.is_unlocked}/>}<DeleteButton action="delete-course" id={course.id} name="courseId" label={`course “${course.title}” and all of its content`}/></div></header>
      {courseChapters.map(chapter=>{const chapterLessons=lessons.filter(item=>item.chapter_id===chapter.id),chapterQuizzes=quizzes.filter(item=>item.chapter_id===chapter.id),chapterActivities=activities.filter(item=>item.chapter_id===chapter.id);return <section className={!selfPaced&&!chapter.is_unlocked?"chapter-block locked":"chapter-block"} id={`chapter-${chapter.id}`} key={chapter.id}><header><span>{chapter.position}</span><div><small>CHAPTER {chapter.position} · {selfPaced?"SEQUENTIAL":chapter.release_mode==="drip"?`DRIP AFTER ${chapter.drip_days} DAYS`:"FREE ACCESS"}</small><h3>{chapter.title}</h3><p>{chapter.description}</p></div><div className="tree-item-actions"><AuthoringModal title={`Review chapter ${chapter.position}`} description="Edit its title, order and guided release settings." buttonLabel="Edit" variant="edit" compact><form action="/api/lms" method="post"><input type="hidden" name="action" value="update-chapter"/><input type="hidden" name="chapterId" value={chapter.id}/><div className="form-row"><label>Position<input name="position" type="number" min="1" defaultValue={chapter.position}/></label><label>Release model<select name="releaseMode" defaultValue={chapter.release_mode} disabled={selfPaced}><option value="free">Free access</option><option value="drip">Drip release</option></select>{selfPaced?<input type="hidden" name="releaseMode" value="free"/>:null}</label></div><label>Title<input name="title" required defaultValue={chapter.title}/></label><label>Description<textarea name="description" rows={4} defaultValue={chapter.description}/></label><label>Drip days<input name="dripDays" type="number" min="1" max="3650" defaultValue={chapter.drip_days||7} disabled={selfPaced}/></label><button>Save chapter</button></form></AuthoringModal>{!selfPaced?<Toggle entity="chapter" id={chapter.id} open={chapter.is_unlocked}/>:null}<DeleteButton action="delete-chapter" id={chapter.id} name="chapterId" label={`chapter “${chapter.title}” and all items inside it`}/></div></header><div className="chapter-items">
        {chapterLessons.map(lesson=><article key={lesson.id}><span><BookOpen size={17}/></span><div><small>LESSON {lesson.position} · {lesson.duration_minutes} MIN</small><strong>{lesson.title}</strong><p>{lesson.summary}</p></div><div className="tree-item-actions"><AuthoringModal title={`Review ${lesson.title}`} description="Edit the learner-facing lesson content and ordering." buttonLabel="Review / edit" variant="edit" compact><form action="/api/lms" method="post"><input type="hidden" name="action" value="update-lesson"/><input type="hidden" name="lessonId" value={lesson.id}/><div className="form-row"><label>Position<input name="position" type="number" min="1" defaultValue={lesson.position}/></label><label>Minutes<input name="duration" type="number" min="5" max="240" defaultValue={lesson.duration_minutes}/></label></div><label>Title<input name="title" required defaultValue={lesson.title}/></label><label>Summary<textarea name="summary" rows={3} required defaultValue={lesson.summary}/></label><label>Lesson HTML<textarea name="content" rows={12} required defaultValue={lesson.content}/><small>Existing embeds and attached resources remain unchanged.</small></label><button>Save lesson</button></form></AuthoringModal>{!selfPaced?<Toggle entity="lesson" id={lesson.id} open={lesson.is_unlocked}/>:null}<DeleteButton action="delete-lesson" id={lesson.id} name="lessonId" label={`lesson “${lesson.title}”`}/></div></article>)}
        {chapterQuizzes.map(quiz=><article className="course-quiz-tree-item" key={quiz.id}><span><FileQuestion size={17}/></span><div><small>{quiz.kind.replaceAll("_"," ")} · {quiz.attempt_limit} attempt{quiz.attempt_limit===1?"":"s"} · pass {quiz.passing_percentage}%</small><strong>{quiz.title}</strong><p>{quiz.questions} of {quiz.question_count} questions ready</p></div><div className="tree-item-actions"><AuthoringModal title={`Questions · ${quiz.title}`} description={`${quiz.questions} of ${quiz.question_count} questions are ready. Add the remaining questions here.`} buttonLabel="Questions" variant="review" compact>{quiz.questions<quiz.question_count?<QuizQuestionBuilder quizId={quiz.id} nextPosition={quiz.questions+1} targetCount={quiz.question_count} returnTo={`/dashboard/tutor/curriculum?quiz=${quiz.id}#chapter-${chapter.id}`}/>:<div className="modal-complete-state"><FileQuestion size={34}/><h3>Question set complete</h3><p>This quiz has all {quiz.question_count} required questions.</p></div>}</AuthoringModal><AuthoringModal title={`Review ${quiz.title}`} description="Edit the title, instructions, pass mark and attempt policy." buttonLabel="Edit" variant="edit" compact><form action="/api/lms" method="post"><input type="hidden" name="action" value="update-quiz"/><input type="hidden" name="quizId" value={quiz.id}/><label>Title<input name="title" required defaultValue={quiz.title}/></label><label>Instructions<textarea name="description" rows={5} required defaultValue={quiz.description}/></label><div className="form-row"><label>Type<select name="kind" defaultValue={quiz.kind}><option value="quiz">Practice quiz</option><option value="assessment">Assessment</option><option value="final_assessment">Final assessment</option></select></label><label>Pass mark<input name="passingPercentage" type="number" min="0" max="100" defaultValue={quiz.passing_percentage}/></label></div><label>Attempts<input name="attemptLimit" type="number" min="1" max="10" defaultValue={quiz.attempt_limit}/></label><button>Save quiz</button></form></AuthoringModal>{!selfPaced?<Toggle entity="quiz" id={quiz.id} open={quiz.is_unlocked}/>:null}<DeleteButton action="delete-quiz" id={quiz.id} name="quizId" label={`quiz “${quiz.title}”`}/></div></article>)}
        {chapterActivities.map(activity=><article key={activity.id}><span><ClipboardList size={17}/></span><div><small>{activity.type} · {activity.points} points</small><strong>{activity.title}</strong><p>Due {new Intl.DateTimeFormat("en-IN",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit",hour12:true}).format(new Date(activity.due_at))}</p></div><div className="tree-item-actions"><AuthoringModal title={`Review ${activity.title}`} description="Edit the activity brief, due time and points." buttonLabel="Review / edit" variant="edit" compact><form action="/api/lms" method="post"><input type="hidden" name="action" value="update-activity"/><input type="hidden" name="activityId" value={activity.id}/><label>Type<select name="type" defaultValue={activity.type}><option value="assignment">Assignment</option><option value="homework">Homework</option><option value="classwork">Class work</option><option value="assessment">Assessment task</option></select></label><label>Title<input name="title" required defaultValue={activity.title}/></label><label>Instructions<textarea name="instructions" rows={6} required defaultValue={activity.instructions}/></label><div className="form-row schedule-row"><DateTimePicker12 name="dueAt" label="Due date and time" defaultValue={activity.due_at.slice(0,16)} required/><label>Points<input name="points" type="number" min="1" max="1000" defaultValue={activity.points}/></label></div><button>Save activity</button></form></AuthoringModal>{!selfPaced?<Toggle entity="activity" id={activity.id} open={activity.is_unlocked}/>:null}<DeleteButton action="delete-activity" id={activity.id} name="activityId" label={`${activity.type} “${activity.title}”`}/></div></article>)}
        {!chapterLessons.length&&!chapterQuizzes.length&&!chapterActivities.length?<div className="chapter-builder-empty"><FolderPlus size={25}/><strong>Chapter ready</strong><p>Use Quick create above to add its first learning item.</p></div>:null}
      </div></section>})}
      {!courseChapters.length?<div className="empty-module"><h3>Add Chapter 1</h3><p>Use the Chapter button above. Every lesson, quiz, assignment and assessment belongs inside a chapter.</p></div>:null}
    </article>})}{!courses.length?<div className="empty-module"><Upload size={28}/><h3>No editable courses yet</h3><p>Create or import a course first, then return to this builder.</p></div>:null}</section>
  </LmsShell>;
}

