import { all } from "@/db/lms";
import { BookOpen, ClipboardList, FileQuestion } from "lucide-react";
import { LmsShell, Notice, Status } from "../../components";
import { requireRole } from "../../auth";
import { MathFormField } from "../../MathComposer";
import LessonAuthoringForm from "./LessonAuthoringForm";
import QuizQuestionBuilder from "../quizzes/QuizQuestionBuilder";
import DeleteButton from "../../DeleteButton";

type Course={id:string;title:string;is_unlocked:number};
type Chapter={id:string;course_id:string;title:string;description:string;position:number;is_unlocked:number};
type Lesson={id:string;course_id:string;chapter_id:string|null;title:string;summary:string;position:number;duration_minutes:number;is_unlocked:number};
type Quiz={id:string;course_id:string;chapter_id:string|null;title:string;kind:string;is_unlocked:number;question_count:number;questions:number;passing_percentage:number};
type Activity={id:string;course_id:string;chapter_id:string|null;title:string;type:string;due_at:string;is_unlocked:number};
type Template={id:string;title:string;subject:string;level:string;description:string;lessons:number};
export const dynamic="force-dynamic";

function Toggle({entity,id,open}:{entity:string;id:string;open:number}){return <form className="mini-unlock" action="/api/lms" method="post"><input type="hidden" name="action" value="set-content-unlock"/><input type="hidden" name="entity" value={entity}/><input type="hidden" name="id" value={id}/><input type="hidden" name="next" value={open?'0':'1'}/><input type="hidden" name="returnTo" value="/dashboard/tutor/curriculum?updated=unlock"/><button>{open?'🔓 Unlocked':'🔒 Locked'}</button></form>}

export default async function Page({searchParams}:{searchParams:Promise<Record<string,string|undefined>>}){
  const profile=await requireRole("tutor","/dashboard/tutor/curriculum"),tutorId=profile.role==='admin'?'usr_demo_tutor':profile.id;
  const courses=await all<Course>("SELECT id,title,is_unlocked FROM courses WHERE tutor_id=? AND status='active' ORDER BY title",tutorId);
  const chapters=await all<Chapter>("SELECT id,course_id,title,description,position,is_unlocked FROM chapters WHERE tutor_id=? ORDER BY course_id,position",tutorId);
  const lessons=await all<Lesson>("SELECT id,course_id,chapter_id,title,summary,position,duration_minutes,is_unlocked FROM lessons WHERE tutor_id=? ORDER BY course_id,chapter_id,position",tutorId);
  const quizzes=await all<Quiz>("SELECT q.id,q.course_id,q.chapter_id,q.title,q.kind,q.is_unlocked,q.question_count,q.passing_percentage,COUNT(qq.id) questions FROM quizzes q LEFT JOIN quiz_questions qq ON qq.quiz_id=q.id WHERE q.tutor_id=? AND q.scope='course' AND q.status='published' GROUP BY q.id ORDER BY q.course_id,q.chapter_id,q.created_at",tutorId);
  const activities=await all<Activity>("SELECT id,course_id,chapter_id,title,type,due_at,is_unlocked FROM activities WHERE tutor_id=? AND status!='closed' ORDER BY course_id,chapter_id,due_at",tutorId);
  const templates=await all<Template>(`SELECT t.id,t.title,t.subject,t.level,t.description,COUNT(l.id) lessons FROM curriculum_templates t LEFT JOIN curriculum_template_lessons l ON l.template_id=t.id WHERE t.status='published' GROUP BY t.id ORDER BY t.title`);
  return <LmsShell profile={profile} activeRole="tutor" activePath="/dashboard/tutor/curriculum" eyebrow="Structured course builder" title="Courses, chapters & learning items" subtitle="Choose a course, add chapters, then place lessons, quizzes, assignments and assessments inside the correct chapter.">
    <Notice params={await searchParams}/>
    <section className="panel tutor-library"><div className="panel-head"><div><span className="panel-kicker">ACADEMY LIBRARY</span><h2>Import curriculum as a structured course</h2></div><Status>{templates.length} packages</Status></div><div className="library-import-grid">{templates.map(template=><article key={template.id}><span className="panel-kicker">{template.subject} · {template.level}</span><h3>{template.title}</h3><p>{template.description}</p><small>{template.lessons} lessons · imports locked</small><form action="/api/lms" method="post"><input type="hidden" name="action" value="import-curriculum"/><input type="hidden" name="templateId" value={template.id}/><button>Import course →</button></form></article>)}</div></section>
    <div className="builder-workflow"><span>1 · Select a course</span><span>2 · Add a chapter</span><span>3 · Add learning items</span><span>4 · Unlock for students</span></div>
    <div className="structured-builder"><section className="course-tree">{courses.map(course=>{const courseChapters=chapters.filter(ch=>ch.course_id===course.id);return <article className="course-tree-card" key={course.id}><header><div><small>COURSE STRUCTURE</small><h2>{course.title}</h2><p>{courseChapters.length} chapters · {lessons.filter(item=>item.course_id===course.id).length} lessons · {quizzes.filter(item=>item.course_id===course.id).length} quizzes/assessments</p></div><Toggle entity="course" id={course.id} open={course.is_unlocked}/></header>{courseChapters.map(chapter=>{const chapterLessons=lessons.filter(item=>item.chapter_id===chapter.id);const chapterQuizzes=quizzes.filter(item=>item.chapter_id===chapter.id);const chapterActivities=activities.filter(item=>item.chapter_id===chapter.id);return <section className={chapter.is_unlocked?'chapter-block':'chapter-block locked'} id={`chapter-${chapter.id}`} key={chapter.id}><header><span>{chapter.position}</span><div><small>CHAPTER {chapter.position}</small><h3>{chapter.title}</h3><p>{chapter.description}</p></div><Toggle entity="chapter" id={chapter.id} open={chapter.is_unlocked}/></header><div className="chapter-items">
      {chapterLessons.map(lesson=><article key={lesson.id}><span><BookOpen size={17}/></span><div><small>LESSON {lesson.position} · {lesson.duration_minutes} MIN</small><strong>{lesson.title}</strong><p>{lesson.summary}</p></div><Toggle entity="lesson" id={lesson.id} open={lesson.is_unlocked}/></article>)}
      {chapterQuizzes.map(quiz=><article className="course-quiz-tree-item" key={quiz.id}><span><FileQuestion size={17}/></span><div><small>{quiz.kind.replaceAll('_',' ')} · pass mark {quiz.passing_percentage}%</small><strong>{quiz.title}</strong><p>{quiz.questions} of {quiz.question_count} questions</p><details className="course-quiz-builder"><summary>{quiz.questions<quiz.question_count?`Add question ${quiz.questions+1}`:"Questions complete"}</summary>{quiz.questions<quiz.question_count?<QuizQuestionBuilder quizId={quiz.id} nextPosition={quiz.questions+1} targetCount={quiz.question_count} returnTo={`/dashboard/tutor/curriculum?quiz=${quiz.id}#chapter-${chapter.id}`}/>:<p>This course quiz has the required {quiz.question_count} questions.</p>}</details></div><div className="tree-item-actions"><Toggle entity="quiz" id={quiz.id} open={quiz.is_unlocked}/><DeleteButton action="delete-quiz" id={quiz.id} name="quizId" label={`quiz “${quiz.title}”`}/></div></article>)}
      {chapterActivities.map(activity=><article key={activity.id}><span><ClipboardList size={17}/></span><div><small>{activity.type}</small><strong>{activity.title}</strong><p>Due {new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short'}).format(new Date(activity.due_at))}</p></div><div className="tree-item-actions"><Toggle entity="activity" id={activity.id} open={activity.is_unlocked}/><a href="/dashboard/tutor/work">Manage →</a></div></article>)}
      {!chapterLessons.length&&!chapterQuizzes.length&&!chapterActivities.length&&<div className="chapter-builder-empty"><strong>Chapter created</strong><p>Add a lesson, quiz, assignment or assessment using the builder.</p></div>}
    </div></section>})}{!courseChapters.length&&<div className="empty-module"><h3>Add Chapter 1</h3><p>Every lesson, quiz, assignment and assessment belongs inside a chapter.</p></div>}</article>})}</section>
    <aside className="curriculum-tools"><div className="form-card"><form action="/api/lms" method="post"><input type="hidden" name="action" value="create-chapter"/><span className="panel-kicker">STEP 1</span><h2>Add chapter</h2><label>Course<select name="courseId" required><option value="">Choose course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Chapter number<input name="position" type="number" min="1" defaultValue="1"/></label><label>Chapter title<input name="title" required placeholder="Chapter 1: Foundations"/></label><label>Description<textarea name="description" rows={3} placeholder="What will the student learn in this chapter?"/></label><label className="check-row"><input type="checkbox" name="isUnlocked"/> Unlock chapter now</label><button>Add chapter →</button></form></div>
    <div className="form-card"><LessonAuthoringForm courses={courses} chapters={chapters}/></div>
    <div className="form-card"><form action="/api/lms" method="post"><input type="hidden" name="action" value="create-quiz"/><input type="hidden" name="scope" value="course"/><input type="hidden" name="returnTo" value="/dashboard/tutor/curriculum?created=quiz"/><span className="panel-kicker">STEP 3</span><h2>Add course quiz or assessment</h2><label>Course<select name="courseId" required><option value="">Choose course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Chapter<select name="chapterId" required><option value="">Choose chapter</option>{chapters.map(ch=><option key={ch.id} value={ch.id}>{courses.find(c=>c.id===ch.course_id)?.title} · Ch {ch.position}: {ch.title}</option>)}</select></label><label>Type<select name="kind"><option value="quiz">Practice quiz</option><option value="assessment">Assessment · one attempt</option><option value="final_assessment">Final assessment · one attempt</option></select></label><MathFormField name="title" label="Title" required compact/><MathFormField name="description" label="Instructions" required multiline compact/><div className="form-row"><label>Questions<select name="questionCount" defaultValue="5"><option value="5">5</option><option value="10">10</option><option value="15">15</option><option value="20">20</option><option value="25">25</option></select></label><label>Pass mark (%)<input name="passingPercentage" type="number" min="0" max="100" defaultValue="60"/></label></div><label>Practice attempts<input name="attemptLimit" type="number" min="1" max="10" defaultValue="3"/></label><small>Add all required questions in the course tree, then unlock the quiz.</small><button>Create course knowledge check →</button></form></div>
    <div className="form-card"><form action="/api/lms" method="post"><input type="hidden" name="action" value="create-activity"/><input type="hidden" name="returnTo" value="/dashboard/tutor/curriculum?created=activity"/><span className="panel-kicker">STEP 4</span><h2>Add assignment or class work</h2><label>Course<select name="courseId" required><option value="">Choose course</option>{courses.map(c=><option key={c.id} value={c.id}>{c.title}</option>)}</select></label><label>Chapter<select name="chapterId" required><option value="">Choose chapter</option>{chapters.map(ch=><option key={ch.id} value={ch.id}>{courses.find(c=>c.id===ch.course_id)?.title} · Ch {ch.position}: {ch.title}</option>)}</select></label><label>Work type<select name="type"><option value="assignment">Assignment</option><option value="homework">Homework</option><option value="classwork">Class work</option><option value="assessment">Assessment task</option></select></label><MathFormField name="title" label="Title" required compact/><MathFormField name="instructions" label="Instructions" required multiline/><div className="form-row"><label>Due date<input name="dueAt" type="datetime-local" required/></label><label>Points<input name="points" type="number" min="1" max="1000" defaultValue="100"/></label></div><label className="check-row"><input type="checkbox" name="isUnlocked"/> Unlock for students now</label><button>Publish work →</button></form></div>
    <div className="form-card"><form action="/api/lms" method="post" encType="multipart/form-data"><input type="hidden" name="action" value="upload-lesson-resource"/><h2>Add lesson resource</h2><label>Lesson<select name="lessonId" required><option value="">Choose lesson</option>{lessons.map(l=><option key={l.id} value={l.id}>{l.title}</option>)}</select></label><label>Display title<input name="title"/></label><label>Learning file<input name="file" type="file" accept=".pdf,.ppt,.pptx,.odp,.zip,.doc,.docx,.odt,.rtf,.txt,.csv,.xls,.xlsx,.ods,image/*,video/*,audio/*" required/><small>Images, video, audio, SCORM ZIP, presentations and common document formats are supported.</small></label><button>Upload resource →</button></form></div></aside></div>
  </LmsShell>;
}
